<?php
//
// Delete all auto-generated custom titles from the database. This effectively
// resets them all so that they will be re-generated as needed.
//

require_once __DIR__ . '/../commandLine.inc';

$deleted = CustomTitle::dbDeleteAllAutoGenerated();
print("Rows deleted: $deleted\n");
print("Now restart memcached for the site so that the titles will start to repopulate right away!\n");
