<?php
/*
* Maintenance script (called via cron) that trims the daily edits table. For now we keep a week lookback
* Daily edits table rows are generated by extensions/wikihow/DailyEdits.class.php
*/

require_once __DIR__ . '/../commandLine.inc';

trimDailyEdits();

function trimDailyEdits() {
	$today = date('Ymd');
	$trimDate = strtotime( '-7 day', strtotime($today) );
	$trimDate = wfTimestamp(TS_MW, $trimDate);
	print "Trimming daily edits with timestamps older than $trimDate\n";

	$dbw = wfGetDB(DB_MASTER);
	$dbw->delete('daily_edits', array("de_timestamp < '$trimDate'"), __FILE__);
	print "Finished trimming daily edits table\n";
}
