<?php

require_once __DIR__ . '/../Maintenance.php';


// update tech testing feedback google sheet
class updateTechTestingFeedbackSheet extends Maintenance {

    public function __construct() {
        parent::__construct();
        $this->mDescription = "import sensitive related wikihows";
    }

	private function emailResults( $message ) {
		$to = new MailAddress("aaron@wikihow.com");

		$from = new MailAddress( "alerts@tools1.wikihow.com" );
		$subject = "update tech testing feedback sheet";
		$endPart = "\n\nGenerated by " . __FILE__ . " on " . gethostname() . "\n";
		UserMailer::send( $to, $from, $subject, $message . $endPart, null, "text/plain; charset=UTF-8" );
	}

	public function execute() {
		$message = '';
		try {
			SpecialTechVerifyAdmin::updateSheet();
		} catch ( Exception $e ) {
			$message = "an error occured in this script:\n";
			$message .= $e->getMessage();
			$this->emailResults( $message );
		}

	}
}


$maintClass = "updateTechTestingFeedbackSheet";
require_once RUN_MAINTENANCE_IF_MAIN;

