<?php

require_once __DIR__ . '/../Maintenance.php';

/**
 * @author Alberto
 */
abstract class WHMaintenance extends Maintenance {

	protected $debug = false;
	protected $emailSender = 'alerts@wikihow.com';
	protected $emailRecipients = null;

	public function __construct() {
		parent::__construct();
		$this->addOption('debug', '');
	}

	public function execute()
	{
		global $wgLanguageCode;
		$this->debug = $this->getOption('debug', false);
		$this->echo("Starting ($wgLanguageCode)" . ($this->debug ? ' (debug)' : '') );
	}

	protected function echo(string $msg, string $level='INFO')
	{
		global $wgLanguageCode;
		$fileName = $this->getFileName();
		$nowStr = (new DateTime())->format('Y-m-d H:i:s');
		$this->output("$fileName | $level | $nowStr | $msg\n");
	}

	protected function mail(string $subject, string $body)
	{
		$fileName = $this->getFileName();
		$body .= "\n ----\n Generated by {$fileName} on " . gethostname();

		if ($this->debug) {
			$this->output("\n--- Email ---\n");
			$this->output("   From: " . $this->emailSender . "\n");
			$this->output("     To: " . ($this->emailRecipients ?? '<NOBODY>') . "\n");
			$this->output("Subject: " . $subject . "\n");
			$this->output("   Body:\n\n" . $body . "\n");
			$this->output("-------------\n\n");
		} elseif ($this->emailRecipients) {
			$to = new MailAddress($this->emailRecipients);
			$from = new MailAddress($this->emailSender);
			UserMailer::send($to, $from, $subject, $body);
		}
	}

	protected function fail(string $msg)
	{
		$subject = $this->getFileName() . ' - error';
		$this->echo($msg, 'FATAL');
		$this->mail($subject, $msg);
		exit(1);
	}

	/**
	 * Get the name of file where the child class lives
	 */
	private function getFileName(): string
	{
		$reflector = new ReflectionClass(get_class($this));
		return basename($reflector->getFileName());
	}

}
