tidy.lo: /tmp/pear/cache/tidy-1.2/tidy.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/tmp/pear/cache/tidy-1.2 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /tmp/pear/cache/tidy-1.2/tidy.c -o tidy.lo 
$(phplibdir)/tidy.la: ./tidy.la
	$(LIBTOOL) --mode=install cp ./tidy.la $(phplibdir)

./tidy.la: $(shared_objects_tidy) $(TIDY_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_tidy) $(TIDY_SHARED_LIBADD)

