<?php

class ExpertBranding {
	
	static $branding = false;	
	
	//run as part of WikihowArticleHTML::processArticleHTML()
	//NOTE: uses the existing $doc object
	public function onProcessArticleHTMLAfter($out) {
		global $wgLanguageCode;
		
		if ($wgLanguageCode == 'en') {	
			//EXPERT BRANDING TEST
			self::brandIt($out, 1);
			// self::brandIt($out, 2);			
		}
		
		return true;
	}
	
	//this uses the phpQuery object already started in WikihowArticleHTML::processArticleHTML()
	private function brandIt($out, $ver) {
		$title = $out->getTitle();
		$user = $out->getUser();
		
		if ($user->isAnon()) {
			$title_check = urlencode($title->getDBKey());
			$isControl = in_array($title_check,  self::$eb_controls_2);
			$isTest = in_array($title_check,  self::$eb_articles_2);

			//do you even test, bro?
			if (!$isControl && !$isTest) return;

			$out->addModules('ext.wikihow.expert_branding');

			//just in the control group? Bye
			if ($isControl) return;
			
			if ($isTest) {
				$out->addModules('ext.wikihow.expert_branding');
				self::$branding = true;

				//get the data
				$verifiers = VerifyData::getByPageId($title->getArticleID());
				$verifier = array_pop( $verifiers ); //last one

				if (empty($verifier) || $verifier->name == '') return;
				
				$dbr = wfGetDB(DB_SLAVE);
				$data = $dbr->selectField(VerifyData::VERIFIER_TABLE, 'vi_info', array('vi_name' => substr($verifier->name,0,10)), __METHOD__);
				$data = json_decode($data);
				
				if ($ver == '1') {
					//turn on test && override with our custom icon
					$test_div = '<div id="eb_test01_on"></div>';
					$icon = '<style type="text/css">
								.sp_expert_icon { background-image: url('.self::getIcon($data).'); }
								#sp_expert { min-height: 55px; }
								.sp_expert_icon {
									width: 44px;
									height: 44px;
									margin: 5px 5px 5px 0;
									border-radius: 22px;
								}
								.sp_expert_text { margin-left: 57px; }
								</style>';
					pq('#intro')->before($test_div.$icon);
				}
				elseif ($ver == '2') {
					//turn on test & remove current expert branding
					$test_div = '<div id="eb_test02_on"></div>';
					$hide_it = '<style type="text/css">#sp_expert { display: none; }</style>';
					pq('#intro')->before($test_div.$hide_it);
					
					$intro_section = pq('#method_toc') ? pq('#method_toc') : pq('#intro h1');
					$html = self::getExpert02($data);
					pq($intro_section)->after($html);
				}
			}
		}
	}
	
	private function getExpert02($data) {
		$vars = array(
			'name' => $data->nameLink ? '<a href="'.$data->nameLink.'" target="_blank" rel="nofollow">'.$data->name.'</a>' : $data->name,
			'blurb' => $data->blurb,
			'date' => $data->date,
			'icon' =>  'background-image: url('.self::getIcon($data).')',
			'hoverBlurb' => $data->hoverBlurb
		);
		
		EasyTemplate::set_path(dirname(__FILE__).'/');
		return EasyTemplate::html('expert_branding02', $vars);
	}
	
	private function getIcon($data) {
		if (!self::$branding) return '';
		if (empty($data)) return '';
		$icon = '';
		
		$path = parse_url($data->image)['path'];
		$title = Title::newFromText(substr($path, 7), NS_IMAGE);
		if ( $title && $title->getArticleID() > 0 ) {

			$file = wfFindFile($title, false);
			$thumb = $file->getThumbnail(100, 100, true, true);
			$icon = wfGetPad($thumb->getUrl());			
		}
		
		return $icon;
	}
	
	private static $eb_articles = array(
		'Make-an-Authorization-Letter',
		'Write-a-Memo',
		'Write-a-Business-Letter',
		'Write-a-Letter-Requesting-a-Favor',
		'End-a-Cover-Letter',
		'Write-a-Feature-Article',
		'Write-Letters-to-the-Editor',
		'Start-a-Paragraph',
		'Write-a-Current-Events-Summary',
		'Dedicate-a-Book',
		'Be-a-Good-Editor',
		'Calculate-Your-Ovulation',
		'Know-When-You-Are-Ovulating',
		'Ovulate-With-PCOS',
		'Recover-from-an-Ectopic-Pregnancy',
		'Recognize-the-Symptoms-of-Polycystic-Ovary-Syndrome',
		'Relieve-Constipation-Quickly-and-Naturally',
		'Heal-Acne-Fast-and-Naturally',
		'Heal-Your-Thyroid-Naturally',
		'Get-Rid-of-Hemorrhoids-Naturally',
		'Get-Rid-of-Brown-Spots-Using-Home-Remedies',
		'Treat-Eczema-Naturally',
		'Take-Garcinia-Cambogia',
		'Reduce-a-Fever-without-Medication',
		'Cure-Hyperacidity-Naturally',
		'Heal-a-Cold-Sore-Naturally',
		'Cure-H.-Pylori-Naturally',
		'Increase-Testosterone-Levels-Naturally',
		'Make-Home-Remedies-for-Diarrhea',
		'Remove-Lice-Using-Tea-Tree-Oil',
		'Treat-Genital-Herpes-Naturally',
		'Get-the-Health-Benefits-of-Cinnamon',
		'Make-a-Simple-Remedy-for-Sore-Throat',
		'Treat-a-Burn-Using-Honey',
		'Reduce-Hemorrhoid-Pain',
		'Heal-the-Lungs-Naturally',
		'Soothe-Sore-Eyes',
		'Heal-a-Urinary-Tract-Infection-Naturally',
		'Use-Aromatherapy-for-Sinus-Infection',
		'Treat-a-Headache-With-Herbs',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Virginia',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Kansas',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-North-Carolina',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Colorado',
		'Apply-for-a-Marriage-License-in-Nevada',
		'Change-Your-Name-in-Maine',
		'Apply-For-a-Marriage-License-in-South-Carolina',
		'Find-Out-Immigration-Status',
		'Change-Your-Name-in-Iowa',
		'Format-a-Legal-Brief',
		'Prepare-for-a-Criminal-Trial',
		'Hire-a-Divorce-Lawyer',
		'File-a-Complaint-Against-Child-Support-Services-in-California',
		'Write-Vendor-Contracts',
		'Understand-Obiter-Dicta-%28Common-Law%29',
		'Choose-a-Personal-Injury-Lawyer',
		'Change-Your-Name-in-North-Dakota',
		'File-a-Small-Claim-Lawsuit-in-San-Diego',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Delaware',
		'File-for-Disability-in-New-York',
		'Disprove-a-Libel-Claim',
		'Change-Your-Name-in-Idaho',
		'Change-Your-Name-in-Massachusetts',
		'Get-Married-in-Oklahoma',
		'Change-Your-Name-in-Minnesota',
		'Change-Your-Name-in-Louisiana',
		'Apply-For-a-Marriage-License-in-Alabama',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Georgia',
		'Apply-for-a-Marriage-License-in-Montana',
		'Select-a-Property-Tax-Attorney',
		'Get-Married-in-Minnesota',
		'Sue-in-Civil-Court',
		'Apply-for-an-H-1B-Visa',
		'Start-a-Medical-Malpractice-Lawsuit-in-New-York',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Illinois',
		'Understand-the-Structure-of-a-Simple-Non-Disclosure-Agreement',
		'Become-an-Intellectual-Property-Attorney',
		'Stop-a-Wage-Garnishment-in-California',
		'Bail-Someone-Out-of-Jail',
		'Get-a-Civil-Annulment',
		'Win-a-Legal-Malpractice-Suit',
		'Deal-With-Legal-Matters-on-a-Budget',
		'Opt-Out-of-a-Class-Action-Lawsuit',
		'Protect-Your-Trademark',
		'File-a-Complaint-With-the-Attorney-General',
		'Change-Your-Name-in-Montana',
		'Avoid-a-Retaliation-Lawsuit',
		'Apply-For-a-Marriage-License-in-Connecticut',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Arizona',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Idaho',
		'Check-a-Patent',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Connecticut',
		'Enforce-a-Child-Support-Order',
		'Become-an-Attorney-in-Florida',
		'Complete-Criminal-Probation',
		'Take-Part-in-a-Class-Action-Lawsuit',
		'Establish-Paternity',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Ohio',
		'Change-Your-Name-in-Delaware',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Texas',
		'Be-a-Lawyer-in-The-Next-7-Years',
		'Report-Phishing',
		'Become-an-Adoption-Lawyer',
		'Write-a-Medical-Power-of-Attorney',
		'Select-a-Medical-Malpractice-Lawyer',
		'Accept-a-Settlement-Offer',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Hawaii',
		'Obtain-Free-Employment-Verification-of-Someone',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Rhode-Island',
		'Prevent-Wrongful-Termination-Lawsuits',
		'Apply-for-Medical-Leave',
		'File-a-Motion-in-Court-Without-an-Attorney',
		'Make-a-Freedom-of-Information-Law-%28FOIL%29-Request-in-New-York-State',
		'Get-Alimony',
		'Find-an-Immigration-Lawyer',
		'Apply-for-Child-Support',
		'Treat-Police-Stops',
		'Get-a-Business-License-in-California',
		'File-for-Emergency-Custody',
		'Get-a-Legal-Description-of-Property',
		'Get-Child-Support',
		'Apply-for-Disability-in-Texas',
		'Report-Disability-Fraud',
		'Appeal-a-Denied-Unemployment-Claim',
		'Get-Legal-Guardianship',
		'Appeal-a-Denied-Workers%27-Compensation-Claim',
		'File-a-Motion-to-Stop-Wage-Garnishment',
		'File-for-Temporary-Custody-in-California',
		'Write-a-Letter-for-Proof-of-Employment',
		'Write-an-Affidavit',
		'Write-Your-Own-Last-Will-and-Testament',
		'Sue-for-Defamation',
		'Find-out-if-You-Have-a-Warrant-Out-for-Your-Arrest',
		'Patent-an-Idea',
		'Change-Your-Name',
		'Legally-Change-Your-Name',
		'Change-Your-Name-in-Hawaii',
		'Get-a-Restraining-Order',
		'Get-Copies-of-Old-W2-Forms',
		'Fight-Your-HOA-%28Homeowner-Association%29',
		'File-Divorce-Papers-Without-an-Attorney',
		'Find-out-if-Someone-Is-in-Jail',
		'Write-an-Incident-Report',
		'Expunge-Your-Criminal-Records',
		'Sue-for-Emotional-Distress',
		'Not-Pay-Child-Support',
		'Get-Power-of-Attorney',
		'Write-a-Police-Report',
		'Find-Out-if-Your-License-Is-Suspended-%28USA%29',
		'Obtain-a-Police-Report',
		'Hire-a-Lawyer-When-You-Have-Low-Income',
		'Report-a-Stolen-Social-Security-Card',
		'Write-a-Sublease-Contract',
		'Make-a-Citizen%27s-Arrest',
		'Apply-For-a-Marriage-License-in-California',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-New-Mexico',
		'Write-a-Codicil',
		'Avoid-Copyright-Infringement',
		'Write-a-Letter-to-Your-Attorney',
		'Check-Your-Driving-Record-Online',
		'Find-a-Notary',
		'Get-a-Divorce-Without-a-Lawyer',
		'Address-a-Letter-to-a-Judge',
		'Address-a-Judge-in-Court',
		'Act-when-the-Police-Pull-You-Over-%28USA%29',
		'Find-Someone%27s-Probation-Officer',
		'Find-Out-if-Someone-Has-a-Life-Insurance-Policy',
		'Write-a-Contract-Addendum',
		'Get-a-New-Birth-Certificate',
		'Transfer-a-House-Deed-to-a-Family-Member',
		'Break-a-Car-Lease',
		'Drop-Charges',
		'Get-a-Copy-of-Your-W-2-from-the-IRS',
		'Win-a-Wrongful-Termination-Lawsuit',
		'Add-a-Spouse-to-a-Deed',
		'Expunge-a-Criminal-Record-in-California',
		'Report-a-Lost-Social-Security-Card',
		'Lower-Child-Support',
		'Assume-a-Mortgage',
		'Sue-Your-Employer',
		'Calculate-Alimony',
		'Be-a-Successful-Lawyer',
		'Avoid-Common-Law-Marriage-in-Texas',
		'Request-Duplicate-W2',
		'Add-a-Spouse-to-a-Car-Title',
		'Get-a-Birth-Certificate',
		'Remove-a-Name-from-a-Mortgage-Without-Refinancing',
		'Write-a-Consulting-Contract',
		'Determine-Who-Is-at-Fault-in-a-Car-Accident',
		'Subpoena-Documents',
		'Write-an-Opening-Statement',
		'File-a-Case-in-Small-Claims-Court',
		'Get-a-New-Social-Security-Number',
		'Notarize-a-Power-of-Attorney',
		'Calculate-Bodily-Injury-Settlements',
		'Remove-a-Deceased-Person-from-a-Deed',
		'Become-a-Legal-Guardian',
		'Get-a-Duplicate-Social-Security-Card',
		'Apply-for-Food-Stamps-in-Florida',
		'Change-Your-Name-in-Texas',
		'Get-Tax-Deductions-on-Goodwill-Donations',
		'File-a-Slander-Lawsuit',
		'Get-a-Marriage-License-%28USA%29',
		'File-for-Separation-in-New-York',
		'Apply-for-a-Marriage-License-in-Pennsylvania',
		'Pass-the-Bar-Exam',
		'Get-Evidence-Thrown-out-in-Court',
		'Write-a-Will-when-You-Have-Children',
		'Apply-for-a-Marriage-License-in-New-York',
		'Find-the-Status-of-a-Social-Security-Claim',
		'Get-Child-Custody',
		'Change-Your-Name-in-California',
		'Apply-for-a-Marriage-License-in-Virginia',
		'Change-Your-Name-in-Florida',
		'Access-Criminal-Court-Records',
		'Address-a-District-Attorney-in-a-Letter',
		'Notarize-a-Document',
		'Sue-a-Doctor',
		'Insure-Your-Engagement-Ring',
		'File-a-Grievance',
		'Avoid-Probate',
		'Complete-a-W9-Tax-Form',
		'Help-a-Friend-Who-Gets-Arrested-in-the-Middle-of-the-Night',
		'Access-Court-Records-Electronically',
		'File-for-Disability-in-California',
		'Apply-For-a-Marriage-License-in-Florida',
		'Counter-Sue',
		'Choose-a-Name-for-a-Law-Firm',
		'File-a-Complaint-Against-a-Realtor',
		'Change-Your-Name-in-New-York',
		'Be-a-Witness-in-Court',
		'Fill-out-an-FMLA-Form',
		'Revoke-Power-of-Attorney',
		'Sue-an-Attorney-for-Malpractice',
		'Cancel-Life-Insurance',
		'Make-a-Citizen%27s-Arrest-in-California',
		'Change-Your-Name-in-Maryland',
		'Dispute-an-Insurance-Total-Loss-on-a-Car',
		'Get-the-Most-from-a-Car-Accident-Claim',
		'Apply-for-a-Marriage-License-in-Michigan',
		'Arrange-Bail-at-No-Cost',
		'Think-Like-a-Lawyer',
		'Add-an-Addendum-to-a-Will',
		'Prepare-a-Power-of-Attorney',
		'Acquire-a-Death-Certificate',
		'Answer-a-Legal-Complaint',
		'Understand-when-Separate-Property-Becomes-Marital-Property',
		'Win-a-Slip-and-Fall-Settlement',
		'Protect-Your-Ideas-Without-a-Patent',
		'File-Probate-in-Florida',
		'Find-a-Good-Divorce-Attorney',
		'Change-Your-Name-in-New-Jersey',
		'Get-California-Unemployment-Benefits',
		'Know-when-to-Fire-Your-Lawyer',
		'Write-a-Vacation-Rental-Contract',
		'Change-Your-Name-in-Virginia',
		'Deal-With-Difficult-Police',
		'Calculate-an-Auto-Insurance-Settlement',
		'Probate-a-Will',
		'Get-a-CDL-License-in-New-York',
		'Find-Out-if-Something-Is-Copyrighted',
		'Write-a-Non-Disclosure-Agreement-%28NDA%29',
		'Write-a-Legal-Brief',
		'Expunge-a-DUI',
		'Become-an-Alaska-Resident',
		'Apply-for-Maternity-Leave',
		'Get-a-Paternity-Test-Done',
		'Behave-in-Court',
		'Minimize-Attorney-Fees',
		'Apply-for-the-Link-Card-in-Illinois',
		'Amend-Nonprofit-Bylaws',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Kentucky',
		'Form-a-Corporation',
		'Appeal-a-Summary-Judgment',
		'Appeal-a-Speeding-Ticket',
		'Win-Your-Personal-Injury-Claim',
		'Change-Your-Name-in-Pennsylvania',
		'Divorce-in-Kentucky',
		'Get-a-Trademark',
		'Get-Power-of-Attorney-in-Texas',
		'Probate-an-Estate-in-Texas',
		'Choose-the-Right-Divorce-Lawyer',
		'Get-a-Legal-Separation-in-California',
		'Prove-Libel',
		'Write-an-Ordinary-Power-of-Attorney',
		'End-Probation-Early-in-Texas',
		'Find-out-if-Someone-is-a-Sex-Offender',
		'Become-a-District-Attorney',
		'Get-Florida-Power-of-Attorney',
		'Get-Married-in-Georgia',
		'Change-Your-Name-in-North-Carolina',
		'Get-a-Divorce-in-Prison',
		'Change-Legal-Guardianship',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Arkansas',
		'Change-Your-Name-in-Oregon',
		'Estate-Plan-With-Blended-Families',
		'Change-Your-Name-in-Nevada',
		'Format-a-Legal-Pleading',
		'Shepardize-a-Case',
		'Expunge-an-Arrest',
		'Write-a-Legal-Memo',
		'Start-the-Probate-Process',
		'Win-in-Small-Claims-Court',
		'Become-a-Notary-in-Florida',
		'Represent-Yourself-in-Court-%28U.S.%29',
		'Determine-Whether-Your-Legal-Fees-Are-Tax-Deductible',
		'File-Taxes-if-You-Worked-in-2-Different-States',
		'Write-a-Durable-Power-of-Attorney',
		'Terminate-an-Easement',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Florida',
		'Become-a-Law-Professor',
		'Become-a-Legal-Secretary',
		'Change-Your-Name-in-Michigan',
		'Claim-Compensation-for-Whiplash',
		'Calculate-Self-Employment-Tax-in-the-U.S.',
		'Know-when-to-Change-Lawyers',
		'Change-Your-Name-in-Tennessee',
		'Become-a-Patent-Lawyer',
		'Win-an-Accident-Settlement',
		'Apply-for-a-Marriage-License-in-Mississippi',
		'Change-Your-Name-in-Illinois',
		'Change-Your-Name-in-Kansas',
		'Apply-for-a-Marriage-License-in-Washington',
		'Change-a-Contract-of-Employment',
		'Know-the-Difference-Between-Soft-Law-and-Hard-Law-%28International-Law%29',
		'Change-Your-Name-in-Connecticut',
		'Know-Your-Rights-If-You%27ve-Been-Arrested-for-Drug-Possession',
		'Address-a-Female-Attorney',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Indiana',
		'Get-Married-in-Tennessee',
		'Change-Your-Name-in-Wisconsin',
		'File-a-Trademark',
		'Appeal-a-Court-Order',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Alabama',
		'Write-a-Law-Essay',
		'Find-a-Good-Family-Law-Attorney',
		'Get-Free-Legal-Advice',
		'Change-Your-Name-in-Kentucky',
		'Change-Your-Name-in-Mississippi',
		'Change-Your-Name-in-Ohio',
		'Understand-the-Ratio-Decidendi-%28Common-Law%29',
		'Convince-Police-to-Reopen-a-Case',
		'Change-Your-Name-in-Nebraska',
		'Write-a-Marriage-Contract',
		'Apply-for-a-Marriage-License-in-Wisconsin',
		'Do-a-Background-Check',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-Iowa',
		'Create-a-Will',
		'Change-Your-Name-in-New-Hampshire',
		'Change-Your-Last-Name-After-Marriage',
		'Respond-if-You-Are-Charged-With-Breach-of-Contract',
		'Change-Your-Name-in-New-Mexico',
		'Apply-For-a-Marriage-License-in-Arizona',
		'Apply-For-a-Marriage-License-in-Alaska',
		'Change-Your-Name-in-Utah',
		'Select-a-Real-Estate-Attorney-for-a-Closing',
		'Calculate-Child-Support',
		'Get-Durable-Power-of-Attorney',
		'Find-a-List-of-Class-Action-Lawsuits',
		'Obtain-a-Copy-of-Your-Birth-Certificate-in-South-Carolina',
		'Apply-for-a-Marriage-License-in-Tennessee',
		'Be-an-Executor',
		'Apply-for-Paternity-Leave',
		'Treat-a-Sting-from-a-Stinging-Nettle',
		'Tell-if-You-Have-Strep-Throat',
		'Check-a-Wound-for-Infection',
		'Cure-an-Ear-Infection',
		'Treat-Road-Rash',
		'Clear-a-Sinus-Infection',
		'Examine-a-Mole',
		'Apply-Sunscreen',
		'Treat-a-Bacterial-Infection',
		'Treat-Thrush',
		'Check-for-Lice',
		'Stay-Safe-in-the-Sun',
		'Prevent-Migraines',
		'Start-Using-Accutane',
		'Treat-Hand-Eczema',
		'Treat-the-Mumps',
		'Clear-Skin-of-an-Allergic-Reaction',
		'Deal-With-an-Itch-That-Occurs-Throughout-the-Night',
		'Know-When-to-Take-Antihistamines',
		'Prevent-Body-Acne',
		'Control-Asthma',
		'Get-Rid-of-Skin-Moles',
		'Recognize-an-Asthma-Attack-in-Children',
		'Write-a-Rejection-Letter',
		'Find-Unique-Names-for-Your-Characters',
		'Be-a-Professional-Content-Writer',
		'Write-Fight-Scenes',
		'Write-a-Mystery-Story',
		'Write-a-Teen-Romance-Story',
		'Get-Started-Writing-a-Book',
		'Create-a-Realistic-Fiction-Character',
		'Start-a-Compare-and-Contrast-Essay',
		'Start-Writing-Articles',
		'Put-on-Academic-Robes-for-a-Graduation-Ceremony',
		'Provide-a-Writing-Sample',
		'Edit-Your-Own-Writing',
		'Write-Children%27s-Short-Stories',
		'Find-a-Catchy-Title-for-Your-Paper%2FEssay'
	);
	
	private static $eb_articles_2 = array(
		'Get-Rid-of-a-Headache',
		'Get-a-Girl-to-Fall-in-Love-with-You',
		'Get-Over-a-Break-Up',
		'Get-Rid-of-a-Hangover',
		'Identify-Different-Dog-Worms',
		'Get-Rid-of-a-Stye',
		'Impress-a-Girl-and-Make-Her-Fall-in-Love-with-a-Boy',
		'Become-a-Model',
		'Tell-if-a-Dog-Is-Pregnant',
		'Make-a-Man-Fall-in-Love-with-You',
		'Make-a-Long-Distance-Relationship-Work',
		'Get-Rid-of-a-UTI-Fast',
		'Recognize-the-Symptoms-of-Appendicitis',
		'Treat-a-Pinched-Nerve',
		'Read-Body-Language',
		'Tell-if-a-Cat-is-Pregnant',
		'Get-Rid-of-a-Stiff-Neck',
		'Relieve-Constipation-Quickly-and-Naturally',
		'Be-Happy',
		'Treat-a-Sting-from-a-Stinging-Nettle',
		'Know-if-Your-Toe-Is-Broken',
		'Find-Your-Passion',
		'Reduce-Excess-Stomach-Acid',
		'Remove-Cat-Urine-Smell',
		'Heal-Acne-Fast-and-Naturally',
		'Deliver-a-Baby',
		'Raise-Blood-Platelet-Level-Naturally',
		'Get-a-Crick-Out-of-Your-Neck',
		'Make-Someone-Fall-in-Love-with-You',
		'Tell-if-You-Have-Strep-Throat',
		'Know-if-You-Are-Ready-to-Have-Sex',
		'Identify-Mange-on-Dogs',
		'Stop-Yourself-from-Crying',
		'Sprint-Faster',
		'Get-Rid-of-Redness-on-the-Face',
		'Express-a-Dog%27s-Anal-Gland',
		'Get-Rid-of-a-Red-Eye',
		'Stop-Eye-Twitching',
		'Stop-Thinking-of-Something-or-Someone',
		'Stop-a-Cat-from-Clawing-Furniture',
		'Get-Happy-when-You%27re-Sad',
		'Determine-the-Sex-of-a-Kitten',
		'Diagnose-and-Treat-Your-Dog%27s-Itchy-Skin-Problems',
		'Get-Any-Boy-to-Fall-in-Love-With-You',
		'Get-a-Woman-to-Fall-in-Love-with-You',
		'Stop-a-Nose-Bleed',
		'Determine-if-Someone-Is-a-Sociopath',
		'Confront-Friends-Who-Are-Ignoring-You',
		'Get-Rid-of-Hemorrhoids-Naturally',
		'Deal-With-Loneliness',
		'Heal-Cuts-Quickly-%28Using-Easy%2C-Natural-Items%29',
		'Check-a-Wound-for-Infection',
		'Be-Mature',
		'Treat-a-Burn',
		'Check-Cats-for-Worms',
		'Bathe-a-Cat',
		'Deal-With-Sexual-Frustration',
		'Diagnose-Vaginal-Discharge',
		'Purposefully-Forget-Things',
		'Get-Rid-of-Brown-Spots-Using-Home-Remedies',
		'Tell-if-a-Betta-Fish-Is-Sick',
		'Treat-Eczema-Naturally',
		'Heal-Chafed-Skin',
		'Train-a-Dog',
		'Make-Your-Dog-Smell-Better',
		'Write-Your-Own-Last-Will-and-Testament',
		'Treat-Dog-Diarrhea',
		'Heal-Your-Thyroid-Naturally',
		'Care-for-Guinea-Pigs',
		'Cure-Mange-in-Dogs',
		'Crate-Train-Your-Dog-or-Puppy',
		'Get-Rid-of-Acne-Scars-with-Home-Remedies',
		'Communicate-with-Your-Cat',
		'Be-a-Good-Person',
		'Tell-How-Old-a-Kitten-Is',
		'Get-Rid-of-Ear-Mites-in-a-Cat',
		'Reduce-a-Fever-without-Medication',
		'Use-Apple-Cider-Vinegar-for-Dogs',
		'Care-for-a-Baby-Wild-Rabbit',
		'Reduce-Menstrual-Cramps',
		'Prevent-Cats-from-Pooping-in-the-Garden',
		'Stop-a-Cat-from-Biting-and-Scratching',
		'Treat-a-Yeast-Infection',
		'Get-Rid-of-Genital-Warts',
		'Handle-a-Dog-Attack',
		'Treat-a-Cough',
		'Cope-With-Frustration',
		'Find-a-Lost-Cat',
		'Get-Rid-of-Acne-Naturally',
		'Tell-if-Your-Cat-Is-in-Heat',
		'Cry-and-Let-It-All-Out',
		'Determine-the-Sex-of-a-Cat',
		'Relieve-a-Tension-Headache',
		'Stop-Crying-when-You-Are-Very-Upset',
		'Care-for-a-Red-Eared-Slider-Turtle',
		'Save-a-Choking-Dog',
		'Be-Positive',
		'Calm-Your-Imagination-Before-Sleep',
		'Cure-Hyperacidity-Naturally',
		'Treat-Heat-Stroke-in-Dogs',
		'Remove-Fiberglass-Slivers-from-Your-Skin',
		'Look-Like-a-Model',
		'Cure-an-Ear-Infection',
		'Know-If-You-Have-Herpes',
		'Feed-a-Newborn-Kitten',
		'Treat-Kennel-Cough',
		'Not-Get-Nervous',
		'Potty-Train-a-Puppy',
		'Litter-Train-a-Kitten',
		'Prepare-Chicken-and-Rice-for-Dogs',
		'Get-Rid-of-Blackheads-on-Your-Nose',
		'Get-Dogs-to-Gain-a-Healthy-Weight',
		'Get-Your-Puppy-to-Stop-Biting',
		'Write-a-Letter-to-a-Judge',
		'Tame-Your-Guinea-Pig',
		'Get-a-Restraining-Order',
		'Know-if-Your-Cat-Is-Sick',
		'Reduce-Excessive-Shedding-in-Dogs',
		'Avoid-Being-Scared-at-Night',
		'Care-for-a-Hamster',
		'Find-a-Federal-Tax-ID-Number',
		'Take-Garcinia-Cambogia',
		'Care-for-Bearded-Dragons',
		'Treat-Worms-in-Dogs',
		'Determine-Your-Dog%27s-Age-By-Its-Teeth',
		'Clear-a-Sinus-Infection',
		'Clean-Your-Dog%27s-Ears',
		'Care-for-a-Rabbit',
		'Deal-with-Being-Nervous',
		'Live-Life-to-the-Fullest',
		'Sue-for-Defamation',
		'Help-a-Cat-Give-Birth',
		'Build-Trust',
		'Identify-Your-Budgie%27s-Gender',
		'Overcome-the-Fear-of-Spiders',
		'Take-Care-of-a-Hedgehog',
		'Cure-a-Cat-of-Constipation',
		'Check-a-Dog-for-a-Fever',
		'Recognize-Syphilis-Symptoms',
		'Get-Your-Ex-to-Fall-for-You-Again',
		'Stop-Being-Paranoid',
		'Surf',
		'Breed-Dogs',
		'Cure-Toenail-Fungus-with-Vinegar',
		'Treat-Road-Rash',
		'House-Train-a-Puppy',
		'Treat-a-Sea-Urchin-Sting',
		'Get-Your-Dog-to-Sleep',
		'Soothe-Sore-Eyes',
		'Pose-for-Pictures',
		'Cure-H.-Pylori-Naturally',
		'Stop-Your-Cat%27s-Diarrhea',
		'Care-for-a-Dog-After-It-Has-Just-Vomited',
		'Patent-an-Idea',
		'Train-a-Puppy-Not-to-Bite',
		'Be-Calm',
		'Clip-Dog-Nails',
		'Find-out-if-You-Have-a-Warrant-Out-for-Your-Arrest',
		'Heal-a-Cold-Sore-Naturally',
		'House-Train-Your-Dog',
		'Take-Care-of-Puppies',
		'Believe-in-Yourself',
		'Change-Your-Name-in-Hawaii',
		'Get-Someone-Committed-to-a-Mental-Hospital',
		'Take-Care-of-a-Parakeet',
		'Gain-Confidence',
		'Build-Self%E2%80%90Control',
		'Get-Dogs-to-Mate',
		'Get-a-Title-to-an-Abandoned-Vehicle',
		'Accomplish-a-Goal',
		'Legally-Change-Your-Name',
		'Change-Your-Name',
		'Help-Your-Dog-Whelp-or-Deliver-Puppies',
		'Remove-Lice-Using-Tea-Tree-Oil',
		'Make-a-Girl-Fall-in-Love-With-You-Fast',
		'Make-a-Kitten-Poop',
		'Gain-Weight-Naturally',
		'Recognize-Scabies-Rash',
		'Calm-a-Cat-in-Heat',
		'Relieve-Constipation-With-Castor-Oil',
		'Communicate-With-Your-Dog',
		'Recognize-Poisoning-in-Dogs',
		'Stop-a-Dog%27s-Quick-from-Bleeding',
		'Take-Care-of-Your-Eyes',
		'Adopt-Your-Stepchild',
		'Pet-a-Cat',
		'Get-a-Girl-to-Fall-for-You',
		'Change-Yourself',
		'Deworm-Cats'	
	);
	
	private static $eb_controls = array(
		'Develop-Good-Soccer-Dribbling-Skills',
		'Get-Over-a-Break-Up',
		'Deal-With-an-Adult%27s-Temper-Tantrum',
		'Live-Life-to-the-Fullest',
		'Heal-From-Rape-and-Sexual-Assault-%28Rape-Trauma-Syndrome%29',
		'Relieve-a-Tension-Headache',
		'Fill-Out-a-Money-Order',
		'Exercise-Your-Eyes',
		'Be-Cheerful',
		'Manage-Conflict',
		'Get-Rid-of-a-Hangover',
		'Naturally-Remove-Blackheads-%28Steam-and-Towel-Method%29',
		'Cope-if-You-Want-to-Become-Anorexic',
		'Incorporate-a-Business',
		'Easily-Clean-Baby%27s-Cradle-Cap-Dandruff-Without-Hurting-the-Baby',
		'Take-Care-of-Your-Eyes',
		'Find-Your-Passion',
		'Be-Happy',
		'Become-a-Model',
		'Stop-Being-Mean-to-People',
		'Get-a-Woman-to-Fall-in-Love-with-You',
		'Treat-a-Sting-from-a-Stinging-Nettle',
		'Beat-Drug-Addiction',
		'Get-a-Girl-to-Fall-in-Love-with-You',
		'Plant-a-Tree',
		'Deal-With-Loneliness',
		'Get-Sober-with-a-12-Step-Program',
		'Cope-With-Panic-Attacks',
		'Love-Somebody',
		'Be-Optimistic',
		'Criticize-Constructively',
		'Clear-a-Sinus-Infection',
		'Thank-Someone',
		'Read-a-Soccer-Penalty-Shot-if-You%27re-a-Goalie',
		'Get-a-Shot',
		'Choose-Stocks',
		'Handle-a-Cheating-Partner',
		'Apologize',
		'Break-a-Habit',
		'Take-Better-Photographs',
		'Tell-if-You-Are-Self-Absorbed',
		'Accomplish-a-Goal',
		'Pose-for-Pictures',
		'Overcome-Your-Fear-of-the-Dentist',
		'Copyright-a-Book',
		'Get-a-Car-Dealer-License-to-Sell-Cars',
		'Repair-Your-Credit',
		'Deal-With-Falling-in-Love',
		'Build-Self-Confidence',
		'Write-a-Check',
		'Survive-a-Negative-Friend',
		'French-Braid',
		'Use-a-Trailing-Stop-Loss',
		'Recognize-Signs-of-an-Abusive-Man',
		'Look-Like-a-Model',
		'Regain-Confidence',
		'Void-a-Check',
		'French-Braid',
		'Use-a-Trailing-Stop-Loss',
		'Recognize-Signs-of-an-Abusive-Man',
		'Avoid-Being-Scared-at-Night',
		'Calm-Your-Imagination-Before-Sleep',
		'Report-Scam-Emails',
		'Look-Like-a-Model',
		'Regain-Confidence',
		'Void-a-Check',
		'Overcome-Serious-Regrets',
		'Budget-Your-Money',
		'Treat-Thrush',
		'Get-Over-an-Embarrassing-Moment',
		'Think-Positively',
		'Express-Your-Emotional-Pain-the-Healthy-Way',
		'Use-a-Stethoscope',
		'Deal-With-the-After-Effects-of-Rape',
		'Invest-Small-Amounts-of-Money-Wisely',
		'Deal-With-Negative-People',
		'Develop-Self%E2%80%90Esteem',
		'Cope-With-Suicidal-Thoughts',
		'Learn-Speed-Reading',
		'Overcome-a-Fear-of-Flying',
		'Help-Someone-with-Depression',
		'Write-a-Living-Will',
		'Deal-With-College-or-University-Rejection',
		'Know-If-Your-Friends-Are-Using-You',
		'Overcome-Sadness',
		'Be-Mature',
		'Kick-a-Soccer-Ball',
		'Deal-With-a-Drug-Addicted-Family-Member-or-Loved-One',
		'Get-a-Job-with-a-Criminal-Record',
		'Stay-Safe-in-the-Sun',
		'Cope-With-Feeling-Alone-at-Night',
		'Deal-with-Guilt',
		'Balance-a-Checkbook',
		'Accept-Being-Shy',
		'Be-Assertive',
		'Make-a-Citizen%27s-Arrest'
	);
	
	private static $eb_controls_2 = array(
		'Eat-a-Fig',
		'Clean-Hard-Water-Spots-Off-Windows',
		'Remove-Watch-Band-Links',
		'Access-a-Router',
		'Prepare-For-a-School-Picture',
		'Calculate-Your-Golf-Handicap',
		'Change-Your-Facebook-Password',
		'Speed-Up-a-Slow-Windows-Computer-for-Free',
		'Be-Emo',
		'Heal-Hemorrhoids',
		'Firm-Your-Breasts',
		'Lose-a-Pound-a-Day',
		'Tell-the-Difference-Between-a-King-Snake-and-a-Coral-Snake',
		'Wash-a-Baseball-Cap-by-Hand',
		'Treat-a-Torn-Toenail',
		'Deodorize-a-Room',
		'Get-More-Matches-on-Tinder',
		'Insert-a-Tampon-for-the-First-Time',
		'Hotwire-a-Car',
		'Do-Superbrain-Yoga',
		'Parallel-Park',
		'Make-a-Cake-Using-a-Pressure-Cooker',
		'Calculate-Confidence-Interval',
		'Delete-Followers-on-Instagram',
		'Get-Rid-of-Lower-Belly-Fat',
		'Make-Eyes-Look-Bigger',
		'Get-Thinner-Thighs',
		'Get-Rid-of-Tooth-Pain',
		'Cook-Fresh-Green-Beans',
		'Cool-Burns-from-Chili-Peppers',
		'Stop-Drooling-in-Your-Sleep',
		'Use-Lemon-Juice-to-Lighten-Hair',
		'Grow-an-Apple-Tree-from-a-Seed',
		'Tell-if-Your-Car%27s-Thermostat-Is-Stuck-Closed',
		'Make-Homemade-Polymer-Clay-Substitute',
		'Stop-a-Sneeze',
		'Identify-a-Hornet',
		'Straighten-Your-Hair-Without-Heat',
		'Add-Multiple-Destinations-on-Google-Maps',
		'Download-a-Movie',
		'Dilate-the-Cervix',
		'Put-on-a-Bra',
		'Fix-a-Laptop-that-is-not-Charging',
		'Uninstall-Google-Chrome',
		'Get-Healthy%2C-Glowing-Skin-%28Men%29',
		'Hide-Your-Phone-Number-%28UK%29',
		'Download-Music-from-Spotify',
		'Spot-Fake-Nikes',
		'Drive-Smoothly-with-a-Manual-Transmission',
		'Add-a-Border-to-Word',
		'Care-for-Your-Nose-Piercing',
		'Drop-Water-Weight',
		'Tell-if-Jade-Is-Real',
		'Check-Your-Health-by-Poop-or-Stool-Colors',
		'Update-Google-Chrome',
		'Get-Rid-of-Foot-Fungus',
		'Analyze-Poop',
		'Access-Another-Computer-from-Your-Computer',
		'Tell-if-a-Person-Is-Using-Cocaine',
		'Build-a-Shed',
		'Add-Music-to-iPhone',
		'Remove-a-Dent-in-Car-With-a-Hair-Dryer',
		'Seduce-an-Older-Woman',
		'Make-a-Natural-Flea-and-Tick-Remedy-with-Apple-Cider-Vinegar',
		'See-Who-Views-Your-Facebook-Profile',
		'Hard-Boil-an-Egg',
		'Keep-a-Cut-Apple-from-Turning-Brown',
		'Make-Your-Hair-Blonder',
		'Unblock-Someone-on-Snapchat',
		'Make-a-Homemade-Protein-Shake-Without-Protein-Powder',
		'Make-Samosas',
		'Grow-Your-Hair-Out-Long',
		'Eliminate-Body-Odor',
		'Cook-Shrimp',
		'Build-a-Big-Chest',
		'Know-when-You-Need-a-Tetanus-Shot',
		'Make-Cool-Stuff-in-Minecraft',
		'Get-Rid-of-a-Scab',
		'Avoid-Having-Sagging-Breasts-as-a-Young-Woman',
		'Get-Taller-Fast',
		'Make-Heavy-Cream',
		'Stay-Motivated-in-School',
		'Dissolve-Kidney-Stones',
		'Type-Emoticons',
		'Lose-Belly-Fat-in-a-Week',
		'Identify-a-Venomous-Snake',
		'Think-of-Stuff-to-Talk-About-with-Your-Boyfriend',
		'Make-Your-Own-Cell-Phone-Jammer',
		'Drink-Absinthe',
		'Get-a-Guy-Who-Has-a-Girlfriend',
		'Make-Virgin-Coconut-Oil',
		'Remove-Hard-Water-Stains-From-Glass',
		'Get-Unbanned-from-Omegle',
		'Do-Magic-Tricks',
		'Hardboil-Eggs-in-a-Microwave',
		'Make-a-Spreadsheet-in-Excel',
		'Unplug-Ears',
		'Activate-Windows-XP-Without-a-Genuine-Product-Key',
		'Clean-the-Oven',
		'Get-Rid-of-Baby-Hiccups',
		'Make-Your-Husband-Happy',
		'Track-an-iPhone',
		'Diagnose-a-Non-Working-Air-Conditioning-in-a-Car',
		'Tell-if-a-Girl-Is-Flirting-With-You',
		'Calculate-Percentage-Increase',
		'Improve-Your-Sex-Life',
		'Take-Care-of-Black-Girls%27-Hair',
		'Freeze-Plums',
		'Get-Rid-of-a-Charley-Horse',
		'Cancel-Planet-Fitness-Membership',
		'Flirt-with-a-Girl-over-Text',
		'Activate-Incognito-Mode',
		'Increase-Your-Appetite',
		'Drink-Apple-Cider-Vinegar',
		'Harvest-Black-Walnuts',
		'Make-Vodka',
		'Decide-What-You-Want-for-Your-Birthday',
		'Apply-Henna-to-Hair',
		'Make-a-Woman-Feel-Better-While-She%27s-on-Her-Period',
		'Make-Instant-Coffee',
		'Get-Rid-of-Weed-Smell',
		'Stretch',
		'Build-a-Robot-at-Home',
		'Make-a-Female-Toga',
		'Find-the-Perimeter-of-a-Triangle',
		'Make-a-Simple-Electric-Generator',
		'Clear-History-on-an-iPhone',
		'Fake-Symptoms-of-Being-Sick',
		'Get-Rid-of-Pigeons',
		'Knit-a-Scarf',
		'Seduce-a-Man',
		'Defrost-a-Freezer',
		'View-Browsing-History',
		'Remove-an-Ingrown-Toenail',
		'Install-Pavers',
		'Call-Private',
		'Open-an-iPhone',
		'Get-Rid-of-Bed-Bugs-at-Home',
		'Press-Flowers',
		'Arouse-Girls',
		'Shave',
		'Lose-Your-Voice-Fast',
		'Identify-a-Hobo-Spider',
		'Tell-a-Guy-You-Like-Him',
		'Remove-Scratches-From-Plastic-Lens-Glasses',
		'Get-a-Six-Pack-Without-Any-Equipment',
		'Make-Chocolate-Chip-Cookies',
		'Paint-a-Car',
		'Make-Friends-in-College',
		'Tie-a-Bandana',
		'Be-Healthy',
		'Do-a-Backflip',
		'Tie-a-Bow-Tie',
		'Get-Rid-of-Mice-Fast',
		'Back-Up-Your-iPhone',
		'Ping-an-IP-Address',
		'Read-Men%27s-Body-Language-for-Flirting',
		'Text-a-Girl-That-You-Like',
		'Pick-a-Good-YouTube-Name',
		'Make-a-Banana-Smoothie',
		'Deal-With-Your-Period',
		'Show-a-Guy-That-You-Like-Him',
		'Get-Stronger-and-Thicker-Wrists',
		'Become-Flexible',
		'Get-Your-Ex-Boyfriend-Back',
		'Block-Caller-ID',
		'Remove-Mold-and-Mildew',
		'Download-Facebook-Videos-For-Free',
		'Land-a-Helicopter-After-Your-Pilot-Has-Been-Killed',
		'Improve-WiFi-Reception',
		'Fix-a-Squeaking-Bed-Frame',
		'Build-3D-Models-of-Animal-and-Plant-Cells',
		'Factor-Second-Degree-Polynomials-%28Quadratic-Equations%29',
		'Avoid-Sweating-Too-Much',
		'Be-Beautiful',
		'Exercise-for-Firmer-Boobs-and-Butts',
		'Establish-an-Effective-Skincare-Routine',
		'Find-the-Magnitude-of-a-Vector',
		'Write-a-Good-Lab-Conclusion-in-Science',
		'Stop-Internet-Popups',
		'Remove-Scratches-from-Glass',
		'Extend-the-Battery-Life-of-an-iPad',
		'Wash-Your-Face',
		'Become-Sexy-%28for-Boys-Only%29',
		'Get-Skinnier-Legs',
		'Keep-Your-Face-Clean',
		'Improve-Your-Singing-Voice-Without-Taking-Singing-Lessons',
		'Get-Rid-of-Chapped-Lips',
		'Make-Vodka-Gummy-Bears',
		'Disconnect-a-Car-Battery',
		'Move-to-England'	
	);
}



