CREATE TABLE `usage_logs` (
  `ul_id` int(11) unsigned NOT NULL auto_increment,
  `ul_user` int(11) NOT NULL,
  `ul_user_text` varchar(256) NOT NULL default '',
  `ul_visitor_id` varbinary(20) NOT NULL default '',
  `ul_event_type` varchar(256) default NULL,
  `ul_event_action` varchar(256) default NULL,
  `ul_label` varchar(256) default NULL,
  `ul_article_id` int(11) default NULL,
  `ul_assoc_id` int(11) default NULL,
  `ul_browser` varchar(256) default '',
  `ul_browser_version` varchar(256) default '',
  `ul_platform` varchar(256) NOT NULL default '',
  `ul_serialized_data` blob,
  `ul_timestamp` varchar(14) NOT NULL default '',
  PRIMARY KEY  (`ul_id`),
  KEY `user_text` (`ul_user_text`(255)),
  KEY `user` (`ul_user`),
  KEY `event_type` (`ul_event_type`(255)),
  KEY `assoc_id` (`ul_assoc_id`),
  KEY `timestamp` (`ul_timestamp`),
  KEY `visitor_id` (`ul_visitor_id`),
  KEY `label` (`ul_label`)
) ENGINE=InnoDB AUTO_INCREMENT=370 DEFAULT CHARSET=utf8;
