<?php
global $IP;

require_once __DIR__ . '/../../commandLine.inc';
require_once ("$IP/extensions/wikihow/DatabaseHelper.class.php");
require_once("$IP/extensions/wikihow/titus/GoogleSpreadsheet.class.php");

$status2s = array('how to 360 mountain bike',
'how to access kindle books on computer',
'how to access privacy settings on instagram',
'how to access the deep web',
'how to achieve enlightenment',
'how to achieve good governance',
'how to achieve universal primary education',
'how to activate ipad without apple id',
'how to activate metro pcs replacement phone',
'how to activate phone with bad esn',
'how to add a light switch',
'how to add apps to smart tv',
'how to add beneficiary',
'how to add contacts to google maps',
'how to add facebook icon',
'how to add facebook plugin to website',
'how to add fluid to transfer case',
'how to add galaxy effect to pictures',
'how to add itunes to ipad 2',
'how to add music to google presentation',
'how to add new slide',
'how to add refrigerant oil',
'how to add to cart',
'how to add work on facebook',
'how to adjust a 3 point hitch',
'how to adjust a clutch',
'how to adjust a clutch cable',
'how to adjust a door',
'how to adjust a lazy susan',
'how to adjust a natural gas regulator',
'how to adjust a recliner chair',
'how to adjust a taylormade r7 driver',
'how to adjust air brakes',
'how to adjust bike brakes',
'how to adjust carburetor on echo weedeater',
'how to adjust chainsaw chain',
'how to adjust clutch pedal',
'how to adjust door closer',
'how to adjust entries',
'how to adjust headlights on ford focus',
'how to adjust honda civic headlights',
'how to adjust hood',
'how to adjust linkage',
'how to adjust mazda 3 headlights',
'how to adjust nike vrs driver',
'how to adjust parking brake on john deere gator',
'how to adjust pressure switch',
'how to adjust r1 driver',
'how to adjust rainbird sprinkler heads',
'how to adjust rbz driver',
'how to adjust roller rockers',
'how to adjust spr',
'how to adjust steering wheel',
'how to adjust suspension',
'how to adjust the carburetor on a kohler engine',
'how to adjust the rbz driver',
'how to adjust torsion bars',
'how to adjust trailer brakes',
'how to adjust trigger pull',
'how to adjust truck brakes',
'how to adjust valves',
'how to adjust water pressure regulator',
'how to administer dibels',
'how to adopt uk',
'how to aim a compound bow',
'how to airbend',
'how to airbrush t shirts',
'how to align camshaft timing marks',
'how to align my hp printer',
'how to alley oop in 2k13',
'how to analyze data',
'how to analyze sentences',
'how to anchor a shed',
'how to anchor a swing set',
'how to animate',
'how to answer the fool',
'how to antique stainless steel',
'how to aquascape',
'how to arsenio',
'how to assemble a bike',
'how to assemble a molle ruck',
'how to assemble a pool table',
'how to assimilate',
'how to attach thule cargo box',
'how to attain siddhi',
'how to attract ghosts',
'how to authorize a device for google music',
'how to avoid huge ships',
'how to bacic',
'how to back half a car',
'how to back up samsung galaxy',
'how to backwash a de filter',
'how to bag a truck',
'how to balayage',
'how to be a dominant master',
'how to be a fierce competitor',
'how to be a good seller',
'how to be a mogul',
'how to be a porn star',
'how to be a producer',
'how to be a sweetheart',
'how to be a tumblr boy',
'how to be a vancouverite',
'how to be a womanizer',
'how to be country',
'how to be hairless',
'how to be like justin bieber',
'how to be sexy in bed',
'how to be thick',
'how to beat ancano',
'how to beat ansem',
'how to beat bald bull',
'how to beat candy crush',
'how to beat candy crush 181',
'how to beat candy crush 197',
'how to beat candy crush level 158',
'how to beat candy crush level 347',
'how to beat candy crush level 92',
'how to beat clop',
'how to beat counterfeit island',
'how to beat escape from detention',
'how to beat galactus',
'how to beat level 125 on candy crush',
'how to beat level 130 on candy crush',
'how to beat level 133 on candy crush',
'how to beat level 135',
'how to beat level 135',
'how to beat level 140 in candy crush',
'how to beat level 153',
'how to beat level 167 in candy crush',
'how to beat level 181 on candy crush',
'how to beat level 224 in pet rescue',
'how to beat level 275 in candy crush',
'how to beat level 288 candy crush',
'how to beat level 38 on candy crush',
'how to beat level 70',
'how to beat level 76',
'how to beat level 77 in candy crush',
'how to beat level 86 in candy crush',
'how to beat level 88 on candy crush',
'how to beat lunar colony',
'how to beat night watch island on poptropica',
'how to beat plague inc',
'how to beat plague inc bacteria',
'how to beat plague inc fungus',
'how to beat planet f',
'how to beat roulette',
'how to beat tabuu',
'how to beat terramorphous',
'how to beat the bookies',
'how to beat the ropebeater',
'how to beat time tangled island',
'how to beat twisted thicket',
'how to become a better trader',
'how to become a demonologist',
'how to become a fhm model',
'how to become a guardian ad litem',
'how to become a male pornstar',
'how to become a member of delta sigma theta',
'how to become a millwright',
'how to become a nascar driver',
'how to become a new zealand citizen',
'how to become a rastafarian',
'how to become a retailer',
'how to become a shaman',
'how to become a soldier',
'how to become a sovereign citizen',
'how to become a star',
'how to become a woman',
'how to become an aka',
'how to become an australian citizen',
'how to become an imam',
'how to become great',
'how to become invisible on zwinky',
'how to become powerful',
'how to become rich and famous',
'how to become web developer',
'how to behave and why',
'how to bench 300',
'how to bench bleed master cylinder',
'how to benchmark',
'how to bend steel',
'how to bet on horses',
'how to bevel a door',
'how to bevel glass',
'how to blacklist on tumblr',
'how to bleed a clutch',
'How to Bleed a clutch master cylinder',
'how to bleed a diesel fuel system',
'how to bleed a ford ranger clutch master cylinder',
'how to bleed a hydraulic clutch',
'how to bleed a power steering pump',
'how to bleed a power steering system',
'how to bleed a towel rail',
'how to bleed abs brakes',
'how to bleed cooling system',
'how to bleed fuel system',
'how to bleed power steering pump',
'how to block a google account',
'how to block friends list in facebook',
'how to block pave',
'how to blog on tumblr',
'how to blow out a sprinkler system',
'how to bodybuild',
'how to book drake',
'how to boot from external hard drive',
'how to boot people off xbox live',
'how to boot people offline',
'how to booty bounce',
'how to booty pop',
'how to bop',
'how to box in a pipe',
'how to box in pipes',
'how to break a curse',
'how to break a fever in a toddler',
'how to break in a new gun',
'how to break into a safe',
'how to break into a sentry safe',
'how to break into a sliding glass door',
'how to break into porn',
'how to break the ice on animal jam',
'how to breed a celtic dragon in dragonvale',
'how to breed a century dragon',
'how to breed a clover dragon on dragonvale',
'how to breed a cyclops dragon',
'how to breed a deedge',
'how to breed a deedge',
'how to breed a diamond dragon in dragon story',
'how to breed a garnet dragon',
'how to breed a gemstone dragon',
'how to breed a gummy dragon in dragon city',
'how to breed a platinum dragon',
'how to breed a river dragon',
'how to breed a sapphire dragon',
'how to breed a shugabush',
'how to breed an aquamarine dragon',
'how to breed clover dragon',
'how to breed harris hawks',
'how to breed legendary dragon',
'how to breed legendary dragon in dragon city',
'how to breed rare dragons in dragon city',
'how to breed trout',
'how to breed villagers',
'how to bronx wine',
'how to bug a cell phone',
'how to build a baja truck',
'how to build a balcony',
'how to build a barbecue',
'how to build a bike',
'how to build a boat',
'how to build a bridge',
'how to build a building',
'how to build a car',
'how to build a chariot',
'how to build a dam',
'how to build a dome',
'how to build a door',
'how to build a fireplace',
'how to build a garage',
'how to build a lake',
'how to build a lawn',
'how to build a lego gun',
'how to build a methane digester',
'how to build a mud motor',
'how to build a murphy bed',
'how to build a pagoda',
'how to build a patio cover',
'how to build a pergola',
'how to build a platform',
'how to build a porch',
'how to build a road',
'how to build a roof',
'how to build a server',
'how to build a shower',
'how to build a smokehouse',
'how to build a smoker',
'how to build a swing set',
'how to build a tower',
'how to build a wall',
'how to build a wall fountain',
'how to build a website from scratch',
'how to build a window',
'how to build a wooden house',
'how to build a workbench',
'how to build apps',
'how to build diana',
'how to build draven',
'how to build fiora',
'how to build garen',
'how to build nasus',
'how to build submarine',
'how to build the plane on mob of the dead',
'how to build yi',
'how to build your own house',
'how to build zac',
'how to butcher a bison',
'how to butcher a goat',
'how to butcher a lamb',
'how to butcher a pig',
'how to butcher a rabbit',
'how to butter a brick',
'how to buy a bugatti',
'how to buy an airplane',
'how to buy chainsaw',
'how to buy penny stocks',
'how to bypass a cdi box',
'how to bypass a heater core',
'how to bypass cinavia',
'how to bypass heater core',
'how to bypass mw3 ps3',
'how to bypass school filters',
'how to bypass sophos',
'how to cable lace',
'how to calculate basis points',
'how to calculate board feet',
'how to calculate btu',
'how to calculate cao2',
'how to calculate carrying capacity',
'how to calculate cbm',
'how to calculate equivalent units',
'how to calculate formal charge',
'how to calculate formal charge',
'how to calculate gfr',
'how to calculate gpm',
'how to calculate heating load',
'how to calculate high school gpa',
'how to calculate insurable earnings',
'how to calculate irr',
'how to calculate marginal benefit',
'how to calculate media impressions',
'how to calculate mmol',
'how to calculate moles',
'how to calculate nominal gdp',
'how to calculate percentages in excel',
'how to calculate real gdp',
'how to calculate rpm',
'how to calculate standard error',
'how to calculate tax',
'how to calculate the resultant force',
'how to calculate theoretical yield',
'how to calculate total assets',
'how to calculate total cost',
'how to calculate total liabilities',
'how to calculate unemployment rate',
'how to calculate vapor pressure',
'how to calibrate a bp cuff',
'how to calibrate digital pocket scale',
'how to call free in pakistan',
'how to call the hogs',
'how to cancel crunch membership',
'how to carve',
'how to carve a pipe',
'how to carve folk figures and a cigar store indian',
'how to carve leather',
'how to cash out cc',
'how to cast out demons',
'how to cast small metal and rubber parts 2nd edition',
'how to castrate a pig',
'how to castrate a rooster',
'how to catch blue fish',
'how to catch croakers',
'how to catch kokanee',
'how to catch tilapia',
'how to center',
'how to center a div',
'how to change a clutch',
'how to change app icons',
'how to change my gmail address',
'how to change time on g shock',
'how to change your age on xbox live',
'how to change your minecraft username',
'how to channel spirits',
'how to charge a 12 volt battery',
'how to charge a 6 volt battery',
'how to charge a capacitor',
'how to charge a deep cycle marine battery',
'how to charge a lawn mower battery',
'how to charge a riding lawn mower battery',
'how to charge olympus camera without charger',
'how to chat on facebook',
'how to cheat at bingo',
'how to cheat at war commander facebook',
'how to cheat deer hunter 2014',
'how to cheat on ruzzle',
'how to check a ballast',
'how to check an scr',
'how to check coil pack',
'how to check crank sensor',
'how to check engine light',
'how to check fluid in transfer case',
'how to check freon level',
'how to check fusible links',
'how to check hash',
'how to check if your lottery ticket is a winner',
'how to check ignition control module',
'how to check iqama status',
'how to check my mmr',
'how to check oil pressure',
'how to check pinion angle',
'how to check powerball',
'how to check saudi arabia iqama status',
'how to check subcooling',
'how to check superheat',
'how to check transmission fluid on toyota tacoma',
'how to choose a camshaft',
'how to choose the right vibram five fingers',
'how to cite universal declaration of human rights',
'how to claim entry',
'how to claim housing benefit',
'how to claim inheritance',
'how to class',
'how to classify functions',
'how to clean penis',
'how to clear level 350 candy crush',
'how to clear recently closed in google chrome',
'how to climb a ladder in wwe 13 ps3',
'how to clone a cell phone',
'how to clone a hard drive',
'how to clone a phone',
'how to clone a sim card',
'how to clone a tree',
'how to clone an iphone',
'how to clone marijuana',
'how to close down facebook page',
'how to close windows in windows 8',
'how to coach',
'how to code a website',
'how to coffered ceiling',
'how to collect information',
'how to collect methane from compost',
'how to color',
'how to compare',
'how to compete with amazon',
'how to complete a t4',
'how to completely erase a hard drive',
'how to compress a car spring',
'how to conduct a review',
'how to configure microsoft outlook',
'how to configure zyxel',
'how to connect 2 monitors',
'how to connect 9 dots with 4 straight lines',
'how to connect a belkin router',
'how to connect a blu ray player to an older tv',
'how to connect a camcorder to a pc',
'how to connect a dvd player to a projector',
'how to connect a microkorg to a computer',
'how to connect a midi keyboard to pro tools',
'how to connect a pc monitor to a mac',
'how to connect a pc to a mac',
'how to connect a push button switch',
'how to connect a pvr',
'how to connect a second monitor to a pc',
'how to connect a three phase motor',
'how to connect asha 501 to pc',
'how to connect banana plugs',
'how to connect blue ray player to internet',
'how to connect broadband to dish network receiver',
'how to connect calor gas bottles',
'how to connect cctv camera to tv',
'how to connect comcast cable box to tv',
'how to connect dell inspiron 1545 to tv',
'how to connect dstv decoder',
'how to connect dvr to tv',
'how to connect engine to transmission',
'how to connect epson xp 400',
'how to connect hdmi to tv',
'how to connect home theater to tv',
'how to connect hose to air compressor',
'how to connect hp deskjet 3050 to wireless router',
'how to connect hp envy to tv',
'how to connect internet to samsung tv wireless',
'how to connect ipad to windows',
'how to connect iphone to itunes',
'how to connect ipod to itunes',
'how to connect kindle fire to internet',
'how to connect my blackberry to my pc',
'how to connect my home theater to my pc',
'how to connect my kindle to my wireless network',
'how to connect my pc to my hdtv',
'how to connect my pc to my tv wirelessly',
'how to connect pc to lg smart tv',
'how to connect psp to tv',
'how to connect rcd',
'how to connect router to modem',
'how to connect samsung galaxy s3 to tv',
'how to connect soundbar to tv',
'how to connect speakers',
'how to connect speakers to receiver',
'how to connect subwoofer to receiver',
'how to connect to a server on a mac',
'how to connect to google chrome',
'how to connect to mifi',
'how to connect to the internet',
'how to connect to uconnect',
'how to connect to windows',
'how to connect tv to cable box',
'how to connect tv to internet',
'how to connect two monitors windows 7',
'how to connect usb to ipad',
'how to connect windows 8 to windows 7',
'how to connect xbox 360 to mac',
'how to connect yahoo mail to facebook',
'how to connect yamaha keyboard to ipad',
'how to contact joe rogan',
'how to contact microsoft',
'how to contact miley cyrus',
'how to contact the dmv',
'how to control a woman',
'how to control adrenaline',
'how to control anger and depression',
'how to control eutrophication',
'how to control fire',
'how to control population',
'how to control sexual urges',
'how to cope with autism',
'how to copy a dvd',
'how to copyright a name',
'how to counter leblanc',
'how to cover up a bad wall',
'how to crack',
'how to crack a wpa password',
'how to crack idm',
'how to crack wifi password',
'how to crack wifi passwords',
'how to create a center of excellence',
'how to create a database',
'how to create a file',
'how to create abundance',
'how to create an income for life',
'how to create an ngo',
'how to create sisterlocks',
'how to crewel embroidery',
'how to crochet a bathing suit cover up',
'how to crochet a bolero',
'how to crochet a skirt',
'how to crochet a sweater',
'how to crochet a vest',
'how to crochet a visor',
'how to crochet baby sweater for beginners',
'how to crochet bolero',
'how to crochet bolero shrug',
'how to crochet butterflies',
'how to crochet twist',
'how to crochet v neck sweater',
'how to croon',
'how to crop video online',
'how to cross hatch',
'how to crouch',
'how to cure cancer',
'how to cure dehydration at home',
'how to cure pseudomonas',
'how to cure sinus infections without antibiotics',
'how to cut a song',
'how to cut a video',
'how to cut and sew iro and buba',
'how to cut angles',
'how to cut glass tile',
'how to cut granite',
'how to cut videos',
'how to date a bulova watch',
'how to day trade',
'how to ddos an ip',
'how to deactivate airbag',
'how to deactivate onstar',
'how to debone a deer',
'how to debug',
'how to deburr sheet metal',
'how to decompile ex4',
'how to defeat ancano',
'how to defend my house in minecraft',
'how to defend your girlfriend',
'how to define variables',
'how to degree a camshaft',
'how to degree a camshaft',
'how to derestrict a moped',
'how to describe a graph',
'how to design',
'how to design a blog',
'how to design an app',
'how to detect a blood clot in the leg',
'how to detect a sound card',
'how to determine a set (in math)',
'how to determine genotype',
'how to determine if a graph is a function',
'how to determine if a relation is a function',
'how to determine reaction rate',
'how to develop an app',
'how to diagnose als',
'how to dial a dsn number',
'how to dim halogen lights',
'how to dim led lights',
'how to direct music',
'how to disable car alarm',
'how to disable drl',
'how to disable parental controls on Android',
'how to disable price peep',
'how to disable speed limiter',
'how to disarm a car alarm',
'how to disassemble a mossberg 500',
'how to disassemble a mossberg 500',
'how to disassemble an ar 15',
'how to disconnect fuel lines',
'how to disconnect onstar',
'how to disconnect onstar gps',
'how to discuss what matters most',
'how to dismantle an atomic bomb',
'how to divide large numbers',
'how to do a 27 piece',
'how to do a barrel roll',
'how to do a bedlam cube',
'how to do a front aerial',
'how to do a heisman',
'how to do a mctwist',
'how to do a mohawk',
'how to do a mohawk weave',
'how to do a rubix cube',
'how to do a running head',
'how to do a swot analysis',
'how to do a valve job',
'how to do an indian accent',
'how to do candy crush level 130',
'how to do cool things',
'how to do cupping',
'how to do dimensional analysis',
'how to do fantasy draft in madden 13',
'how to do figure 8 on motorcycle',
'how to do fishbone diagram',
'how to do functions',
'how to do gas pedal',
'how to do ice tables',
'how to do input output tables',
'how to do istikhara',
"How to do Kids'' Hair",
'how to do level 13 on 40xescape',
'how to do level 133 candy crush',
'how to do lighthouse on kendama',
'how to do limiting reactant problems',
'how to do limits',
'how to do long division polynomials',
'how to do mphil',
'how to do nalbinding',
'how to do nauli',
'how to do parabolas',
'how to do pat testing',
'how to do pinstriping',
'how to do poetic justice braids',
'how to do postmortem',
'how to do quillwork',
'how to do sculptured nails',
'how to do sisterlocks',
'how to do statistics',
'how to do the mcgeady spin',
'how to do the oghma infinium glitch',
'how to do the rednose',
'how to do the tarantella',
'how to do the tupler technique',
'how to do toes to bar',
'how to do topiary',
'how to do unit rate',
'how to do variables',
'how to do vat returns',
'how to do yoga',
'how to double coupons',
'how to double knit',
'how to double your money',
'how to downgrade 3ds',
'how to downgrade 6.0 to 5.1 1',
'how to downgrade itunes',
'how to downgrade ps3',
'How To Download And Watch FIFA World Cup Videos',
'how to download black ops 2',
'how to download dayz',
'how to download facebook',
'how to download flash',
'how to download games',
'how to download heart of the swarm',
'how to download heart of the swarm',
'how to download microsoft office',
'how to download paid apps for free',
'how to download pdf',
'how to download pictures',
'how to download pixelmon',
'how to download shows from netflix',
'how to download to ipad',
'how to download tv shows',
'how to downshift',
'how to drain a boiler',
'how to drain central heating system',
'how to draw an astronaut',
'how to drench a goat',
'how to drench sheep',
'how to drift an automatic car',
'how to drill',
'how to drill a circle',
'how to drill a hole in a computer desk',
'how to drill a square hole',
'how to drill stainless steel bolts',
'how to drive a boat',
'how to drop in',
'how to dry hop',
'how to dry marijuana',
'how to dry out dirt',
'how to dunk in 2k13',
'how to dunk in 2k13',
'how to dunk on nba 2k14',
'how to duplicate diamonds in minecraft',
'how to duplicate items in minecraft pe',
'how to dyno tune',
'how to earn vc in nba 2k13',
'how to eat to live',
'how to email people on craigslist',
'how to embed literacy and numeracy skills in vocational',
'how to emulsion walls',
'how to enclose a porch',
'how to end a hexafish',
'how to end poverty',
'how to enjoy sex',
'how to enlarge an image',
'how to enter international markets',
'how to establish residency',
'how to estimate quotients',
'how to euthanize a cat',
'how to evaluate',
'how to evolve axew',
'how to evolve feebas',
'how to evolve happiny',
'how to evolve lairon',
'how to evolve lampent',
'how to evolve lombre',
'how to expand expressions',
'how to explain sex to kids',
'how to export',
'how to extract broken spark plug',
'how to extract gold from rocks',
'how to extract platinum from catalytic converters',
'how to extreme coupon at walmart',
'how to factory reset',
'how to factory unlock iphone 4',
'how to factory unlock iphone 4 at&t',
'how to fast forward time in dragon city',
'how to fasten Android',
'how to feather edge fencing',
'how to feng shui',
'how to fiberglass a dash',
'how to field dress a hog',
'how to field dress a moose',
'how to field strip a 1911',
'how to fight someone stronger than you',
'how to figure out gst from a total',
'how to file a motion in court',
'how to fill form 15ca',
'how to fill out a pink slip',
'how to find asymptotes',
'how to find bulova model number',
'How To Find Cheap Flights To The FIFA World Cup',
'how to find clients',
'how to find critical points',
'how to find eigenvectors',
'how to find enthalpy',
'how to find gold',
'how to find standard deviation on ti 84',
'how to find the limiting reactant',
'how to find the sum',
'how to finish a quilt',
'how to finish stairs',
'how to fish umbrella rig for bass',
'how to fit a back box',
'how to fit a chimney cowl',
'how to fit a curtain rail',
'how to fit a freestanding bath',
'how to fit a gas strut',
'how to fit a gate latch',
'how to fit a kitchen',
'how to fit a thermostatic shower valve',
'how to fit a yale lock',
'how to fit gas struts',
'how to fit loft insulation',
'how to fit oil cooler',
'how to fit pigs ear handrail',
'how to fit rhino roof racks',
'how to fit roof rails',
'how to fix a car',
'how to fix a head gasket',
'how to fix a phone',
'how to fix a ps3',
'how to fix an android tablet',
'how to fix anything',
'how to fix garbage disposal',
'how to fix iphone 4 screen',
'how to fix lock button on iphone 4',
'how to fix ntldr is missing',
'how to fix washing machine',
'how to fix windows 7',
'how to fix ylod',
'how to flash a phone to metro pcs',
'how to flash a samsung galaxy ace',
'how to flash a sprint phone to boost',
'how to flash c3322',
'how to flintknap',
'how to flip 200 dollars',
'how to flush a transmission',
'how to flush transmission',
'how to forge',
'how to format hp compaq',
'how to format macbook pro',
'how to format ssd drive',
'how to frag coral',
'how to frame a window',
'how to free a seized engine',
'how to free motion quilt',
'how to free ride',
'how to freeze',
'how to front feeble',
'how to gain accreditation',
'how to gain followers',
'how to gamble',
'how to gameshare on ps3',
'how to gank',
'how to garden in texas',
'how to gas pedal',
'how to get 4g lte',
'how to get 999 rare candies',
'how to get a 6 pack in a week',
'how to get a free car',
'how to get a free iphone',
'how to get a golden key in borderlands 2',
'how to get a lot of rare candies in pokemon soul silver',
'how to get a medicare card',
'how to get a mob head',
'how to get a pardon',
'how to get a pink slip',
'how to get a twic card',
'how to get abs for men',
'how to get abs in 2 weeks',
'how to get an air dragon',
'how to get an obama phone',
'how to get around school blocks',
'how to get av line',
'how to get barrel for free',
'how to get better at black ops 2',
'how to get big boobs',
'how to get celtic dragon',
'how to get cocaine out of your system',
'how to get cut',
'how to get cydia apps for free',
'how to get cydia on ios 6',
'how to get dimples',
'how to get endorsements',
'how to get exalted with lorewalkers',
'how to get feathers in angry birds',
'how to get fox sports in the uk',
'how to get free amazon gift cards',
'how to get free donuts in simpsons tapped out',
'how to get free facebook credits',
'how to get free gems in clash of clans',
'how to get free gems in dragonvale',
'how to get free gems in dragonvale',
'how to get free gumballs from a gumball machine',
'how to get free hbo',
'how to get free in app purchases',
'how to get free in app purchases with cydia',
'how to get free kindle books',
'how to get free microsoft points 2013',
'how to get free packs in madden 25',
'how to get free ps vita games',
'how to get free psn codes',
'how to get free rp',
'how to get free stuff',
'how to get free tf2 items',
'how to get free vip on weeworld',
'how to get free xbox live gold',
'how to get full screen on facebook',
'how to get gears of war judgment beta',
'how to get genesect',
'how to get girlcraft',
'how to get gold keys in borderlands 2',
'how to get ifile',
'how to get infinite ammo in resident evil 6',
'how to get intelliscreenx for free ios 6',
'how to get internet on xbox 360',
'how to get into mount hyjal',
'how to get into olympics',
'how to get into space',
'how to get involved',
'how to get jelly bean on galaxy s3',
'how to get keldeo',
'how to get keldio',
'how to get marijuana (thc) out of your system fast',
'how to get meloetta',
'how to get more fps',
'how to get more lives on candy crush saga',
'how to get mywi 6 for free',
'how to get mywi 6 for free',
'how to get nuketown 2025',
'how to get nuketown zombies',
'how to get nuketown zombies free',
'how to get on the show bad ink',
'how to get on top of the plane on terminal mw3',
'how to get orange weapons in borderlands 2',
'how to get paid apps for free',
'how to get people to do stuff',
'how to get permanent juggernog',
'how to get phd flopper in die rise',
'how to get pheromones',
'how to get pictures from instagram',
'how to get player heads on minecraft',
'how to get popular on instagram',
'how to get rayquaza',
'how to get rid of a dry throat',
'how to get rid of an abscess',
'how to get rid of peeling skin',
'how to get rid of pus pockets in throat',
'how to get rid of smelly gas',
'how to get rid of voles',
'how to get ripped fast',
'how to get round shoulders',
'how to get scopus id',
'how to get shredded',
'how to get sisterlocks',
'how to get sky for free',
'how to get sky sports for free online',
'how to get sovereignty',
'how to get sponsored',
'how to get the bee shield',
'how to get the ebony blade in skyrim',
'how to get the middle finger emoji',
'how to get the peacekeeper',
'how to get the superbike for free',
'how to get through rock tunnel',
'how to get to brooklyn',
'how to get to dread wastes',
'how to get to hollywood',
'how to get to isle of giants',
'how to get to isle of thunder',
'how to get to kun lai summit',
'how to get to nex',
'how to get to rikers island from the bronx',
"how to get to serpent''s overlook",
'how to get to shrine of seven stars',
'how to get to terramorphous',
'how to get to the isle of giants',
'how to get to townlong steppes',
'how to get traded in nba 2k13',
'how to get tristana for free',
'how to get unlimited gems in clash of clans',
'how to get unmuted',
'how to get women in bed',
'how to get xbox live gold free',
'how to give',
'how to give a khutbah',
'how to give birth',
'how to give birth to a baby',
'how to give birth to twins',
'how to give iv medication',
'how to go by train',
'how to go into labor faster',
'how to go mo',
'how to go to college almost for free',
'how to go to the moon in minecraft',
'how to grade a test',
'how to graft a fruit tree',
'how to graph absolute value',
'how to graph absolute value',
'how to graph y 2',
'how to graph y 3x',
'how to ground',
'how to ground a generator',
'how to group email',
'how to grow a lemon tree',
'how to grow a pineapple top',
'how to grow a queen palm',
'how to grow dragon fruit',
'how to grow hemp',
'how to grow kush',
'how to grow reggie',
'how to grow your boobs',
'how to hack a 3ds',
'how to hack a cell phone',
'how to hack a email account',
'how to hack a facebook account for free',
'how to hack a macbook pro',
'how to hack a minecraft account',
'how to hack a minecraft server',
'how to hack a twitter account',
'how to hack a vending machine',
'how to hack a wifi password',
'how to hack an instagram account',
'how to hack black ops 2',
'how to hack cars in gt5',
'how to hack castle clash',
'how to hack clash of clans',
'how to hack clash of clans Android',
'how to hack clash of clans with cydia',
'how to hack clash of clans with cydia',
'how to hack clash of clans with ifile',
'how to hack deer hunter 2014',
'how to hack dragon city gems',
'how to hack dragon city with cheat engine',
'how to hack ebay account',
'how to hack fb account',
'how to hack games',
'how to hack google',
'how to hack google',
'how to hack growtopia',
'how to hack gta 5 online',
'how to hack gta 5 online',
'how to hack head soccer',
'how to hack in cod4',
'how to hack instagram',
'how to hack into a facebook account',
'how to hack into an iphone',
'how to hack moviestarplanet',
'how to hack on black ops 2',
'how to hack onstar',
'how to hack osm',
'how to hack pokemon y',
'how to hack ps3',
'how to hack real racing 3',
'how to hack smartphone',
'how to hack social wars cash',
'how to hack someones instagram',
'how to hack someones snapchat',
'how to hack subway surfers',
'how to hack text plus',
'how to hack xbox 360',
'how to hack xbox 360 games',
'how to hack yahoo email',
'how to hack youtube accounts',
'how to hallucinate without drugs',
'how to handicap horses',
'how to handicap horses',
'how to hang a european mount',
'how to hang bikes in garage',
'how to hang glide',
'how to hatch ender dragon egg',
'how to have a baby on sims freeplay',
'how to have a successful relationship',
'how to have children in minecraft',
'how to have more sex',
'how to have sex with someone with herpes',
'how to have that difficult conversation you ve been avoiding',
'how to headspace a rifle',
'how to help your spouse heal from your affair a compact manual for the unfaithful',
'how to hide pipes in kitchen',
'how to hide toolbars',
'how to hit a 3 wood',
'how to hit a 7 iron',
'how to hit a fade',
'how to hit on women',
'how to hitch horsehair',
'how to hold a knife',
'how to hone a cylinder',
'how to hook up 2 amps',
'how to hook up a blu ray player',
'how to hook up a dishwasher',
'how to hook up a gas stove',
'how to hook up a linear amplifier to a cb radio',
'how to hook up a magic jack',
'how to hook up a relay',
'how to hook up a router',
'how to hook up a sega genesis to a flat screen',
'how to hook up aftermarket fuel gauge',
'how to hook up an amp',
'how to hook up an ice maker',
'how to hook up cable',
'how to hook up crystal surround air track',
'how to hook up dish network dual receiver',
'how to hook up soundbar to tv',
'how to hook up trailer lights',
'how to hook up tweeters',
'how to hook up vizio soundbar to lg tv',
'how to host modded lobbies',
'how to hotwire a atv',
'how to identify a mauser rifle',
'how to identify a snake',
'how to identify a turtle',
'how to identify a vw transmission',
'how to identify an insect',
'how to identify bacteria',
'how to identify cocaine',
'how to identify wm rogers silverware patterns',
'how to impeach a president',
'how to implement daily 5',
'how to improvise',
'how to increase gfr',
'how to increase sperm motility',
'how to increase torque',
'how to increase volume',
'how to incubate eggs',
'how to initiate sex',
'how to inject into a vein',
'how to innovate',
'how to insert a pessary',
'how to insert a running head',
'how to insert boot media',
'how to insert boric acid suppositories',
'how to insert ng tube',
'how to install a 350 engine',
'how to install a backwater valve',
'how to install a batwing fairing',
'how to install a bike rack',
'how to install a blow off valve',
'how to install a blower motor in a car',
'how to install a boiler',
'how to install a boost gauge',
'how to install a carburetor',
'how to install a ceiling medallion',
'how to install a check valve for an aquarium',
'how to install a clutch',
'how to install a clutch cable',
'how to install a cold air intake',
'how to install a cold water storage tank',
'how to install a combi boiler diagram',
'how to install a convertible top',
'how to install a cork floor',
'how to install a crate engine',
'how to install a culvert',
'how to install a deck',
'how to install a door closer',
'how to install a door lock',
'how to install a door sweep',
'how to install a dryer',
'how to install a dual battery system in a boat',
'how to install a fifth wheel hitch',
'how to install a fireplace',
'how to install a flat screen tv in a motorhome',
'how to install a fluidmaster',
'how to install a free floating quad rail',
'how to install a front bumper cover',
'how to install a front mount intercooler',
'how to install a fuel pressure regulator',
'how to install a fuel pump',
'how to install a furnace',
'how to install a gas cap',
'how to install a gate latch',
'how to install a hasp',
'how to install a header beam',
'how to install a heat pump',
'how to install a heated towel rail',
'how to install a heater core',
'how to install a hob',
'how to install a junction box',
'how to install a kill switch',
'how to install a lift kit',
'how to install a lift kit on a ford f150',
'how to install a light switch',
'how to install a line level converter',
'how to install a lip kit',
'how to install a lock nut',
'how to install a lower control arm',
'how to install a magic mesh',
'how to install a multi fuel burning stove',
'how to install a new wall sconce',
'how to install a nmea 2000 network',
'how to install a pellet stove',
'how to install a pond liner',
'how to install a porch ceiling',
'how to install a pressure reducing valve',
'how to install a pressure switch',
'how to install a rack and pinion',
'how to install a radon mitigation system',
'how to install a rca line out converter',
'how to install a roof',
'how to install a roof rack',
'how to install a sand point',
'how to install a satellite dish',
'how to install a security door',
'how to install a sequential gearbox',
'how to install a shifter cable',
'how to install a shurflo water pump',
'how to install a snow fence',
'how to install a ssd',
'how to install a subfloor',
'how to install a supercharger',
'how to install a switch',
'how to install a thermocouple',
'how to install a thetford cassette toilet',
'how to install a trailer hitch',
'how to install a trailer hitch on a dodge ram 1500',
'how to install a transmission',
'how to install a transmission cooler',
'how to install a turbo kit',
'how to install a turbo timer',
'how to install a upvc window',
'how to install a vanity',
'how to install a vapor barrier',
'how to install a vessel sink',
'how to install a winch on a truck',
'how to install aether 2',
'how to install afn satellite dish',
'how to install agi pipe',
'how to install air conditioner in window',
'how to install air fuel ratio gauge',
'how to install airport extreme',
'how to install allure flooring',
'how to install an aftermarket cd player',
'how to install an air filter',
'how to install an electric hob',
'how to install an exterior prehung door',
'how to install an ice maker water line',
'how to install an oil pan gasket',
'how to install Android on a non Android phone',
'how to install android on hp touchpad',
'how to install Android on windows phone',
'how to install ap trap',
'how to install apk',
'how to install arabic language on Android',
'how to install backup camera',
'how to install bem gauges',
'how to install besta suspension rail',
'how to install blower motor',
'how to install bluetooth',
'how to install broan bathroom fan',
'how to install bushings',
'how to install cedar shingles',
'how to install cedar siding',
'how to install ceiling light',
'how to install check valve',
'how to install click lock flooring',
'how to install coil spring spacers',
'how to install commercial door closer',
'how to install corner blocks',
'how to install cpanel',
'how to install crash bars',
'how to install cyanogenmod',
'how to install daytime running lights',
'how to install dayz',
'how to install deck railing',
'how to install differential gears',
'how to install dirt bike seat cover',
'how to install door handle lights',
'how to install door jamb extensions',
'how to install downdraft ventilation',
'how to install downpipe',
'how to install drain tile',
'how to install drip edge',
'how to install driving lights diagram',
'how to install durock',
'how to install dvd shrink',
'how to install emg hz pickups',
'how to install engineered wood flooring',
'how to install epo',
'how to install expansion tank',
'how to install extaliams',
'how to install fallout 3 mods',
'how to install fascia',
'how to install fender flares',
'how to install flywheel',
'how to install fml',
'how to install fog lights on toyota yaris',
'how to install french doors',
'how to install frp',
'how to install fuel pump',
'how to install fusion on xbmc',
'how to install gable vent',
'how to install google play',
'how to install gooseneck hitch',
'how to install halo headlights',
'how to install harmonic balancer',
'how to install headers',
'how to install headers on silverado',
'how to install headphones',
'how to install heat tape',
'how to install helical piers',
'how to install helicoil',
'how to install hid lights',
'how to install hinges',
'how to install honda odyssey roof rails',
'how to install hot foot throttle',
'how to install hp deskjet 3050a',
'how to install hp deskjet f2400 series',
'how to install ice maker',
'how to install ikea butcher block countertop',
'how to install in Android',
'how to install indoor outdoor carpet',
'how to install installous',
'how to install joist hangers',
'how to install kitchen sink',
'how to install lace closure',
'how to install lazy susan hardware',
'how to install leveling kit f150',
'how to install levolor universal mount shade brackets',
'how to install lift kit on golf cart',
'how to install lifters',
'how to install lightroom presets',
'how to install line lock',
'how to install load resistors',
'how to install loft hatch',
'how to install logitech webcam',
'how to install mac on pc',
'how to install magic jack plus',
'how to install mame',
'how to install master controller sims 3',
'how to install medicine cabinet',
'how to install megasquirt',
'how to install metal cladding',
'how to install motor mount inserts',
'how to install msn on windows 8',
'how to install mutant creatures mod',
'how to install mutant creatures mod 1.6 4',
'how to install navi x',
'how to install nerf bars on a dodge ram',
'how to install nerf bars on dodge ram',
'how to install nest thermostat',
'how to install neutral safety switch',
'how to install nitrous',
'how to install occupancy sensor',
'how to install officers',
'how to install oil pan gasket',
'how to install oil pressure gauge',
'how to install onstar fmv',
'how to install patch',
'how to install pedal covers',
'how to install peel and stick tile',
'how to install photoshop cs6 for free',
'how to install piston rings',
'how to install pixelmon',
'how to install plugins',
'how to install plugmold',
'how to install power steering',
'how to install quick release steering wheel',
'how to install recirculating hot water',
'how to install recon tail lights',
'how to install roll pan',
'how to install roll pan on silverado',
'how to install roof flashing',
'how to install rough country dual steering stabilizer',
'how to install running boards',
'how to install rv solar system',
'how to install screen',
'how to install sd card in Android',
'how to install selkirk stove pipe',
'how to install sena smh10',
'how to install serpentine belt',
'how to install shifter',
'how to install siding over stucco',
'how to install sim card in Android',
'how to install sks muzzle brake',
'how to install sky magic eye',
'how to install snaps',
'how to install snow fence plastic',
'how to install soffit vents',
'how to install sony walkman mp3 player',
'how to install spoiler',
'how to install steam on chromebook',
'how to install sun visor',
'how to install sunroof wind deflector',
'how to install super bluetooth hack on Android',
'how to install swanstone shower walls',
'how to install synthetic rope on winch',
'how to install t 111 siding',
'how to install terraria mods',
'how to install themes for windows 7',
'how to install thermal expansion tank',
'how to install track lighting',
'how to install trailer brake controller on 2012 silverado',
'how to install trailer lights',
'how to install truck tool box',
'how to install turbo kits',
'how to install turbo oil lines',
'how to install tv antenna',
'how to install tweeters',
'how to install ubuntu on chromebook',
'how to install underlayment',
'how to install universal door lock actuator',
'how to install vanity lights',
'how to install vapor barrier',
'how to install vinyl lattice',
'how to install warn winch',
'how to install water temperature gauge',
'how to install wheel spacers',
'how to install wheel studs',
'how to install wheel tubs',
'how to install wifi at home',
'how to install windlace',
'how to install windows',
'how to install windows 7 in hp laptop',
'how to install windows 7 on mac',
'how to install windows 7 on new hard drive',
'how to install windows 7 on ssd drive',
'how to install windows 7 on windows 8',
'how to install windows 8 on android tablet',
'how to install windows on Android tablet pc',
'how to install wood flooring on concrete',
'how to insulate a cargo trailer',
'how to insulate a pole barn',
'how to insulate crawl space',
'how to insulate loft',
'how to intubate a patient',
'how to invest $100000',
'how to invest in gold',
'how to investigate someone',
'how to irrigate a foley catheter',
'how to issue refund',
'how to jack up a car',
'how to jack up a house',
'how to jack up a truck',
'how to jailbreak a ps3',
'how to jailbreak a tablet',
'how to jailbreak an android phone',
'how to jailbreak an ipad',
'how to jailbreak an ipad 2',
'how to jailbreak an iphone 4s',
'how to jailbreak an xbox 360',
'how to jailbreak apple tv',
'how to jailbreak apple tv 3',
'how to jailbreak ios 6',
'how to jailbreak ios 6 untethered',
'how to jailbreak iphone 4 without computer',
'how to jailbreak ipod 4',
'how to jailbreak ipod touch 4g without computer',
'how to jailbreak ps3',
'how to jailbreak your phone',
'how to jam gps signal',
'how to jig',
'how to join a clan in clash of clans',
'how to join a country club',
'how to join anonymous',
'how to join arsenal academy',
'how to join barcelona',
'how to join facebook',
'how to join in the round',
'how to join kitchen worktops',
'how to join pmc',
'how to join the hells angels',
'how to join the lcpd',
'how to join the raf',
'how to join ymcmb',
'how to jtag with a usb',
'how to jtag xbox 360',
'how to juke',
'how to jungle',
'how to keep score in spades',
'how to keep your volkswagen alive',
'how to keylog someone',
'how to kill a tree',
'how to kill ancano',
'how to kill mr house',
'how to kill rajinikanth',
'how to kill slender man',
'how to kill spongebob',
'how to kill terramorphous',
'how to kill the ball',
'how to kill viscidus',
'how to kill w4r d3n',
'how to kitbash structures',
'how to knit a hat',
'how to knit a hat with straight needles',
'how to knit a sweater',
'how to knit in the round',
'how to know what to believe',
'how to lace a bmx wheel',
'how to land a plane',
'how to last longer in bed naturally',
'how to launch an app',
'how to lay a tarmac drive',
'how to lay block',
'how to lay cement',
'how to lay ceramic floor tile',
'how to lay concrete slabs',
'how to lay flooring',
'how to lay granite setts',
'how to lay moisture barrier',
'how to lay oak flooring',
'how to lay rocks landscaping',
'how to lay rolled roofing',
'how to lay turf lawn preparation',
'how to lay wall tile',
'how to layout a square to round transition',
'how to learn html5',
'how to learn photography',
'how to learn photoshop',
'how to legitimize a child',
'how to level up fast in borderlands 2',
'how to level up fast in borderlands 2',
'how to level up in black ops 2 zombies',
'how to lift a golf cart',
'how to light a fire',
'how to line a dress',
'how to line a jacket',
'how to lip lock',
'how to live in an rv',
'how to live in texas',
'how to livestream black ops 2',
'how to ln',
'how to load a 22 rifle',
'how to load a quilt on a long arm',
'how to load a semi',
'how to load a tank',
'how to load a winchester model 190',
'how to load plug in',
'how to lock natural hair',
'how to lock your car and why',
'how to log into powerschool',
'how to look up a docket number',
'how to lose 10 pounds in 2 days',
'how to lose 100 pounds in 3 months',
'how to lose 15 pounds in a month',
'how to lose 20 pounds in 2 weeks',
'how to lose 20 pounds in a week',
'how to lose 30 or 40 pounds fast',
'how to lose 30 or 40 pounds in 3 months',
'how to lose 30 pounds in a month',
'how to lose 40 pounds in a month',
'how to lose 5 pounds in 2 days',
'how to lower a motorcycle',
'how to lower crp',
'how to maintain an erection',
'how to make 1000 dollars fast',
'how to make 1000 dollars in a week',
'how to make 10000',
'how to make 3d shapes',
'how to make a backpack',
'how to make a ball',
'how to make a bb gun',
'how to make a boat',
'how to make a bracer',
'how to make a bracket',
'how to make a bridge',
'how to make a calculator',
'how to make a car',
'how to make a caterpillar',
'how to make a chart',
'how to make a chibi',
'how to make a couch',
'how to make a cow',
'how to make a cylinder',
'how to make a dodecahedron',
'how to make a drawer',
'how to make a drift trike',
'how to make a duck call',
'how to make a dynamometer',
'how to make a fairy',
'how to make a fan',
'how to make a fist',
'how to make a flower',
'how to make a gauntlet',
'how to make a good emblem on black ops 2',
'how to make a guitar',
'how to make a homemade microphone',
'how to make a homemade pipe',
'how to make a homemade taser',
'how to make a hood',
'how to make a key',
'how to make a labyrinth',
'how to make a latex mask',
'how to make a lego gun that shoots',
'how to make a library in minecraft',
'how to make a malt',
'how to make a man desire you',
'how to make a minecraft costume',
'how to make a minecraft mod',
'how to make a mini gun',
'how to make a mob trap',
'how to make a molar solution',
'how to make a moonshine still',
'how to make a motorcycle seat',
'how to make a mountain',
'how to make a murphy bed',
'how to make a murphy bed',
'how to make a nasal rinse',
'how to make a paper ak 47',
'how to make a paper bomb',
'how to make a paper gauntlet',
'how to make a paper kite step by step',
'how to make a paper uzi',
'how to make a periscope out of pvc pipe',
'how to make a phone',
'how to make a presentation',
'how to make a pump drill',
'how to make a railroad spike knife',
'how to make a rectangular prism',
'how to make a robot for kids',
'how to make a rug',
'how to make a sabiki rig',
'how to make a sale',
'how to make a server',
'how to make a shirt',
'how to make a shotgun',
'how to make a skull',
'how to make a sniper rifle',
'how to make a speaker',
'how to make a sphere',
'how to make a steve head',
'how to make a steve head',
'how to make a submarine',
'how to make a tail',
'how to make a tessellation',
'how to make a time bomb',
'how to make a triple single rainbow loom',
'how to make a tumblr theme',
'how to make a ufo',
'how to make a video online',
'how to make a virtual machine',
'how to make a volcano out of paper',
'how to make a water wall',
'how to make a whale',
'how to make a works bomb',
'how to make a zippy chain rainbow loom',
'how to make all purpose flour',
'how to make an alcohol thermometer',
'how to make an atom model',
'how to make an axe',
'how to make an ecosphere',
'how to make an ender dragon',
'how to make an enema',
'how to make an eye of ender',
'how to make an origami ball',
'how to make android apps',
'how to make antibiotics',
'how to make apps',
'how to make assassins creed hidden blade',
'how to make bake',
'how to make binding for a quilt',
'how to make black',
'how to make boots',
'how to make brass knuckles',
'how to make bullets',
'how to make contractions stronger',
'how to make cool stuff',
'how to make cornstarch',
'how to make fire with an orange',
'how to make glowstone',
'how to make gray',
'how to make hydrochloric acid',
'how to make iron',
'how to make land perk',
'how to make life in little alchemy',
'how to make maizena',
'how to make money in stocks',
'how to make ninja stars',
'how to make pants',
'how to make rainbow loom rings',
'how to make roads in minecraft',
'how to make sales',
'how to make sex interesting',
'how to make stone steps',
'how to make the wind dragon',
'how to make water',
'how to make windows 7 genuine',
'how to make your apps look cool',
'how to make your arms longer',
'how to make your butt bigger naturally',
'how to make your butt smaller',
'how to make your feet smaller',
'how to make your hairline grow back',
'how to make your ps3 faster',
'how to make youtube video available on mobile',
'how to manscape',
'how to manually close a sunroof',
'how to map a process',
'how to master the art of selling',
'how to measure a curve',
'how to measure air pollution',
'how to measure altitude',
'how to measure camshaft',
'how to measure caravan awning size',
'how to measure density',
'how to measure electricity',
'how to measure intensity',
'how to measure kpi',
'how to measure length',
'how to measure voltage',
'how to measure wheel bolt pattern',
'how to measure wheelbase',
'how to measure/calculate pressure',
'how to measure/determine longitude',
'how to meet john cena',
'how to meet johnny depp',
'how to meet justin bieber',
'how to meet niall horan',
'how to meet one direction',
'how to meet ross lynch',
'how to meg a motor',
'how to megger a motor',
'how to migrate from easy cliq to easy starter',
'how to miter crown molding',
'how to mitre skirting board',
'how to mix',
'how to mix diazinon',
'how to mix names',
'how to mod borderlands 2',
'how to mod call of duty black ops 2',
'how to mod gta 4',
'how to mod gta 4 ps3',
'how to mod gta 5',
'how to mod gta 5',
'how to mod gta 5 online',
'how to model in maya',
'how to modify suzuki 4x4 for serious off road action',
'how to mount a scope',
'how to mount a scope on a ruger 10 22',
'how to mount a tv in a corner',
'how to mount a winch',
'how to mount bipod',
'how to mount buffalo horns',
'how to mount tv on rv wall',
'how to mount tv on tv stand',
'how to mute',
'how to name a plane',
'how to navigate',
'how to needlepoint a belt',
'how to neutralize ph',
'how to open an ipod touch 4g',
'how to open back cover of sony xperia',
'how to open charles',
'how to open diz file',
'how to open electric gate',
'how to open eml files',
'how to open fire fyter safe',
'how to open idx files',
'how to open otterbox defender',
'how to open pdf files',
'how to open sh files',
'how to open trunk without key',
'how to order plexus slim',
'how to overclock gpu',
'how to overcome physical barriers',
'how to override a veto',
'how to pack a punch on tranzit',
'how to paint citadel miniatures',
'how to pair',
'how to pass a drug test in 24 hours',
'how to pass a drug test in 24 hours',
'how to pass charlie and the chocolate factory',
'how to pass etg test',
'how to pass level 103 on candy crush',
'how to pass level 117 candy crush',
'how to pass level 152 candy crush',
'how to pass level 265 on candy crush',
'how to pass level 91 candy crush',
'how to pass mouth swab test',
'how to pass mouth swab test',
'how to pass the apmp a study guide',
'how to passivate stainless steel at home',
'how to pasteurize',
'how to pay employees',
'how to pay sallie mae with credit card',
'how to perform a megger test',
'how to perform at test',
'how to perform homam',
'how to pick a door lock',
'how to pick a sentry safe lock',
'how to pick lucky numbers',
'how to pick up with a woman on facebook',
'how to pick your dragon',
'how to picmix',
'how to pierce your own nipple',
'how to ping a cell phone',
'how to pinstripe',
'how to pinstripe for beginners',
'how to place 2 pictures side by side',
'how to plasti dip rims',
'how to play 100 doors of revenge',
'how to play 100 floors',
'how to play 2 player on resident evil 6',
'how to play anipang',
'how to play bad piggies',
'how to play basketball',
'how to play dayz',
'how to play fantasy baseball',
'how to play fifa 13',
'how to play gta san andreas on facebook',
'how to play madden 13',
'how to play nba 2k13',
'how to play pet rescue saga',
'how to play resident evil 6 split screen',
'how to play slender',
'how to play starcraft 2',
'how to play stay by rihanna on piano',
'how to play the lottery',
'how to play thrift shop on alto saxophone',
'how to play thrift shop on piano',
'how to play when i was your man on piano',
'how to play xbox games on pc',
'how to plot points',
'how to plow a field',
'how to polish petrified wood',
'how to pollinate fruit trees',
'how to poop at work',
'how to position a bedpan',
'how to power macerator',
'how to power tune rover v 8 for road & track',
'how to pre order games',
'how to preach',
'how to preorder',
'how to prep',
'how to prepare a wet mount slide step by step',
'how to preserve a fox tail',
'how to press a bearing',
'how to prestige in black ops 2',
'how to prevent food shortage',
'how to prevent sinkholes',
'how to prime a diesel',
'how to prime a diesel engine',
'how to print photos from canon printer',
'how to print white ink on black paper',
'how to process turkey',
'how to program a chamberlain garage door opener',
'how to program a garage door opener',
'how to program a ge universal remote',
'how to program a pca pump',
'how to program a philips universal remote',
'how to program a ritetemp thermostat',
'how to program a universal remote',
'how to program a vizio tv',
'how to program an onn universal remote',
'how to program directv genie remote',
'how to program eproms',
'how to program garage door opener',
'how to program intermatic timer',
'how to program rca remote',
'how to program time warner remote',
'how to program viper remote',
'how to program vtech cordless phone',
'how to program wow remote',
'how to program xfinity remote',
'how to promote inclusion',
'how to properly insulate a crawl space',
'how to prophesy',
'how to propose an amendment',
'how to prospect',
'how to protect your liver',
'how to prove',
'how to prove 0 0 2',
'how to prove constructive dismissal',
'how to prove embezzlement',
'how to prove gambling losses',
'how to prove the collatz conjecture',
'how to pull a steering column',
'how to pull an engine',
'how to purchase a suppressor',
'how to purge a propane tank',
'how to put a ball closure ring in',
'how to put a cot together',
'how to put a gumball machine back together',
'how to put a hood scoop on',
'how to put a jeep liberty in 4 wheel drive',
'how to put a molle ruck together',
'how to put a motor on a bike',
'how to put a patch on a game',
'how to put a total gym 1000 together',
'how to put emoticons on instagram',
'how to put icon on desktop ipad',
'how to put my signature on my photos',
'how to put on a condom with foreskin',
'how to put together a puzzle ring',
'how to put together a sleep number bed',
'how to put transformers together',
'how to put two pictures together',
'how to put up blinds in a conservatory',
'how to quilt as you go',
'how to r',
'how to rabbet',
'how to raise a ceiling',
'how to raise a dragon',
'how to raise worms',
'how to reach malshej ghat from kalyan',
'how to reach the masses',
'how to read a micrometer',
'how to read blueprints',
'how to reboot windows 7',
'how to rebuild a 305 engine',
'how to rebuild a 700r4 transmission',
'how to rebuild a 727 transmission',
'how to rebuild a carburetor',
'how to rebuild a fan clutch',
'how to rebuild a hydraulic cylinder',
'how to rebuild a manual transmission',
'how to rebuild a starter',
'how to rebuild a transmission',
'how to rebuild air compressor',
'how to rebuild an atomizer',
'how to rebuild brake caliper',
'how to rebuild johnson fuel pump',
'how to rebuild kohler engine',
'how to rebuild small block mopar engines',
'how to rebuild transfer case',
'how to rebuild turbo 350',
'how to rebuild walbro carb',
'how to rebuild your small block ford',
'how to recall a mayor',
'how to recane a chair',
'how to receive',
'how to recharge salik',
'how to recharge tata sky',
'how to reconnect bm622i',
'how to record',
'how to record audio on pc',
'how to record screen',
'how to record video on pc',
'how to record xbox 360 gameplay',
'how to record your computer screen',
'how to record your screen',
'how to recover',
'how to recover a motorcycle seat',
'how to recover deleted files',
'how to redial',
'how to reduce air compressor noise',
'how to reduce voltage',
'how to reface a fireplace',
'how to register a firearm',
'how to regrow hair',
'how to reinstall cydia',
'how to reinstall windows 8 without cd',
'how to release a bowling ball',
'how to relieve pressure points',
'how to reloop',
'how to remodel a bathroom',
'how to remove a bushing without a press',
'how to remove a chimney',
'how to remove a clutch',
'how to remove a clutch cable',
'how to remove a curse',
'how to remove a cyst on my back',
'how to remove a drive shaft',
'how to remove a driveshaft',
'how to remove a fan clutch',
'how to remove a fender on a car',
'how to remove a fireplace',
'how to remove a fireplace insert',
'how to remove a foley catheter',
'how to remove a freeze plug',
'how to remove a harmonic balancer',
'how to remove a moen kitchen faucet',
'how to remove a mole with iodine',
'how to remove a privet hedge',
'how to remove a radiator',
'how to remove a steering column',
'how to remove a stuck spark plug',
'how to remove a sun visor',
'how to remove a teleflex boat steering wheel',
'how to remove a tooth at home',
'how to remove a transmission',
'how to remove a tv stand',
'how to remove ad yieldmanager com',
'how to remove an automatic shifter knob',
'how to remove an engine',
'how to remove artex',
'how to remove axle cap on hand truck',
'how to remove back seats',
'how to remove baseboards',
'how to remove bezel',
'how to remove bmw e46 headlights',
'how to remove broken spark plug',
'how to remove broken spark plug from head',
'how to remove caliper pins',
'how to remove car radio',
'how to remove catalytic converter',
'how to remove cinavia',
'how to remove content lock',
'how to remove dashboard',
'how to remove door panel on 2003 chevy silverado',
'how to remove drawers',
'how to remove driveshaft from transmission',
'how to remove f250 radio',
'how to remove front clip',
'how to remove front grill',
'how to remove gearbox',
'how to remove glazing beads from upvc',
'how to remove gmc emblem from grill',
'how to remove intake manifold',
'how to remove iphone case',
'how to remove jailbreak',
'how to remove jb weld',
'how to remove jeep hardtop by yourself',
'how to remove kohler shower valve',
'how to remove lock ring',
'how to remove locking gas cap lost key',
'how to remove mcgard wheel locks',
'how to remove oven door kitchenaid',
'how to remove parging',
'how to remove pickup coil from distributor',
'how to remove power steering pump pulley',
'how to remove radiator',
'how to remove radio from 2001 mitsubishi montero sport',
'how to remove rain x',
'how to remove rav4 radio',
'how to remove rear quarter panel',
'how to remove rear seat f150',
'how to remove rear seats',
'how to remove running boards',
'how to remove steering shaft',
'how to remove steering wheel',
'how to remove storefront glass',
'how to remove swingarm bolt',
'how to remove tensioner pulley bolt',
'how to remove the door panel on a 2003 ford expedition',
'how to remove third brake light',
'how to remove this site may harm your computer',
'how to remove toenail',
'how to remove transmission',
'how to remove transmission shift cable',
'how to remove troy bilt trimmer head',
'how to remove vw engine',
'how to remove water from gas tank',
'how to remove water from oil tank',
'how to remove watermarks from photos',
'how to remove white smoke',
'how to renew bus pass online',
'how to renew twic card',
'how to rent a condo',
'how to rent to own',
'how to repair a maytag washer',
'how to repair a sewing machine',
'how to replace a floor in a travel trailer',
'how to replace a kitchen faucet',
'how to replace a pickup coil',
'how to replace a thermopile on a gas fireplace',
'how to replace a transmission control solenoid',
'how to replace a transmission solenoid pack',
'how to replace a transmission speed sensor',
'how to replace bath taps with shower mixer',
'how to replace battery in michael kors watch',
'how to replace bottom seal on garage door',
'how to replace double glazed units in windows',
'how to replace glass cooktop on frigidaire',
'how to replace head gasket on 2001 pt cruiser',
'how to replace heater core 1999 dodge durango',
'how to replace heater core in ford expedition',
'how to replace ignition switch on ford f150',
'how to replace iphone 4 screen',
'how to replace ipod touch screen',
'how to replace motor mounts',
'how to replace o2 sensor on cadillac cts',
'how to replace pto clutch on cub cadet',
'how to replace rear axle seals',
'how to replace shift solenoid on a 4l60e',
'how to replace side mirror jeep grand cherokee',
'how to replace spark plugs on a 2003 ford expedition',
'how to replace sun visor on 2008 toyota camry',
'how to replace tongue and groove siding',
'how to replace valve seals without removing the head',
'how to replace valve stem seals without removing the head',
'how to replace vw bug floor pans',
'how to replace water filter on ge profile refrigerator',
'how to replace wiper blades on jaguar s type',
'how to report reliability',
'how to represent a vector',
'how to res',
'how to rescreen a pool cage',
'how to reseat a power adapter',
'how to reset a computer',
'how to reset a hp photosmart printer',
'how to reset a motorola blur',
'how to reset airbag light',
'how to reset Android tablet pattern lock',
'how to reset ecu',
'how to reset ink cartridge',
'how to reset tire pressure light',
'how to reset tpms on 2008 nissan altima',
'how to reset vizio remote',
'how to respond to interrogatory questions',
'how to restart mighty monsters',
'how to restore a vw beetle',
'how to restore an ipad',
'how to restore google chrome',
'how to restore macbook pro',
'how to restrain someone',
'how to resuscitate a child',
'how to retire at 55',
'how to retrieve',
'how to reupholster a recliner',
'how to reupholster a wingback chair',
'how to reupholster car seats',
'how to reuse contaminated water',
'how to reverse a van',
'how to reverse arthritis',
'how to reverse diabetes',
'how to reverse video',
'how to revive a puppy',
'how to rig a fishing line',
'how to rmp',
'how to roll a cross joint',
'how to root a zte warp',
'how to root acer a1 810',
'how to root an android tablet',
'how to root Android 2.3 6',
'how to root Android without pc',
'how to root droid razr maxx hd',
'how to root galaxy s3',
'how to root htc evo 4g',
'how to root htc evo 4g lte',
'how to root htc inspire',
'how to root htc inspire',
'how to root htc sensation',
'how to root htc thunderbolt',
'how to root kindle fire',
'how to root lg optimus g pro',
'how to root lg optimus l9',
'how to root my blackberry',
'how to root nexus 4',
'how to root nexus 4',
'how to root nexus 7',
'how to root samsung galaxy tab 3',
'how to root toshiba thrive',
'how to root your phone',
'how to root zte Android phone',
'how to rope a calf',
'how to round cents',
'how to run a lathe',
'how to satisfy your man',
'how to save a gif',
"how to save bluestar''s life",
'How To Save Money During The World Cup',
'how to scale a load',
'how to schedule a road test',
'how to score a deer',
'how to score high on the caliper profiling test',
'how to score the des',
'how to scout for deer',
'how to script',
'how to seal a door',
'how to search for people',
'how to see instagram photos that are private',
'how to see the fourth dimension',
'how to select a column',
'how to select bearings for a shaft',
'how to sell btc',
'how to sell your car',
'how to separate',
'how to separate mixtures',
'how to separate sectional sofa',
'how to seperate metals',
'how to set a bulova watch',
'how to set a conibear trap',
'how to set a ge light timer',
'how to set a light timer',
'How to Set an Animated GIF as a Desktop Background on Windows',
'how to set an armitron watch',
'how to set an atomic clock',
'how to set intermatic timer',
'how to set memory seats',
'how to set pinion angle',
'how to set realmlist',
'how to set rocker arms',
'how to set the timing on a 2002 pt cruiser',
'how to set up a fluval 405 filter',
'how to set up a tivo',
'how to set up a turbo',
'how to set up dreambox',
'how to set up duck decoys',
'how to set up fisher price interactv',
'how to set up itunes',
'how to set up mbox',
'how to set up sky on demand',
'how to set up slingbox',
'how to set up smart tv',
'how to set up speakers',
'how to set up surround sound speakers',
'how to setup aprs',
'how to setup gateway',
'how to setup toshiba smart tv',
'how to sex rhode island red chicks',
'how to sex turkeys',
'how to sext',
'how to sext your boyfriend',
'how to sharpen a hatchet',
'how to sharpen ice auger blade',
'how to sharpen tungsten carbide',
'how to sheet a roof with osb',
'how to shen',
'how to shift a 13 speed transmission',
'how to shim a starter',
'how to shoot',
'how to shoot a bow',
'how to shoot double trap',
'how to shoot like a navy seal',
'how to shoot sporting clays',
'how to shoot yourself in gta 5',
'how to shop for free',
'how to shrink a leather jacket',
'how to side a house',
'how to sight in a crossbow scope',
'how to sight in a pistol',
'how to sight in a red dot scope',
'how to sign up for hungercraft',
'how to sign up for scared straight program',
'how to simplify polynomials',
'how to simplify rational exponents',
'how to simplify trigonometric expressions',
'how to size a cupola',
'how to size a heat pump',
'how to sketch',
'how to ski moguls',
'how to skin a bear',
'how to skin a beaver',
'how to skin a bobcat',
'how to skin a bobcat for pelt',
'how to skin a coyote',
'how to skin a fox',
'how to skin a gator',
'how to skin a gray fox',
'how to skip trowel',
'how to skip trowel texture',
'how to slaughter a chicken',
'how to slaughter a pig',
'how to slide on a longboard',
'how to smelt copper',
'how to smoke a black and mild',
'how to snake a toilet',
'how to solder a pl 259 connector',
'how to solder wires',
'how to solve a megaminx cube',
'how to solve an equation',
'how to solve equations',
'how to solve ethical issues',
'how to solve multi step equations',
'how to solve subsets',
'how to solve the equation',
'how to solve y mx b',
'how to sort gmail by sender',
'how to soundproof a door',
'how to source candidates',
'how to spawn',
'how to spawn herobrine xbox 360',
'how to speak in tongues',
'how to speed up acer aspire one',
'how to spit game to a girl',
'how to spr',
'how to spy on a cell phone',
'how to ssh into iphone',
'how to stabilize a deck',
'how to stain concrete floors',
'how to start a community center',
'how to start dragonborn dlc',
'how to start sisterlocks',
'how to stay away from women',
'how to sti',
'how to stiffen rear suspension',
'how to stipple a gun',
'how to stop purging',
'how to stream on twitch',
'how to stretch ligaments',
'how to stretch motorcycle leathers',
'how to string a brine clutch 2x',
'how to string a traverse rod',
'how to strip for your boyfriend',
'how to stroke an engine',
'how to style your braids',
'how to subnet',
'how to subsistence farm',
'how to survive ps3',
'how to survive the loss of a love',
'how to suture',
'how to switch verizon phones',
'how to sync music from itunes to ipod',
'how to sync polar loop',
'how to take a tire off a rim',
'how to take apart a 1911',
'how to take apart a door',
'how to take apart a fishing reel',
'how to take apart a lorcin 380 pistol',
'how to take apart a picture frame',
'how to take apart a rainbow vacuum',
'how to take apart an ipod',
'how to take apart price pfister kitchen faucet',
'how to take good photos with canon 600d',
'how to take iphone 4 apart',
'how to take off',
'how to take the back off an iphone',
'how to talk dirty to your boyfriend',
'how to talk your way to success',
'how to tattoo a rabbit',
'how to teach participial phrases',
'how to tell if a circuit breaker is bad',
'how to tell if a dog is a girl or boy',
'how to tell if alternator is going bad',
'how to tell if beats are fake',
'how to tell if u joints are bad',
'how to tell which iphone you have',
'how to test a cdi box',
'how to test a crankshaft position sensor',
'how to test a knock sensor',
'how to test a limit switch on a gas furnace',
'how to test a map sensor',
'how to test a polaris cdi box',
'how to test a stator',
'how to test a thermocouple',
'how to test air quality',
'how to test crank sensor',
'how to test for mthfr',
'how to test for proteins',
'how to test fuel pressure regulator',
'how to test tube baby',
'how to test whirlpool dryer motor',
'how to thatch a roof',
'how to thicken blood before surgery',
'how to thread a babylock',
'how to thread a barrel',
'how to thread an elnita sewing machine',
'how to throw a bowling ball',
'how to throw grenades in tomb raider',
'how to tighten a chain',
'how to tighten a chain on a kawasaki mojave',
'how to tighten beats by dre',
'how to tighten faucet handle',
'how to tighten water pump pulley',
'how to tighten your motorcycle chain',
'how to tile a kitchen floor',
'how to tile a picture in word',
'how to tile around a tub',
'how to tile stairs',
'how to tilt front end',
'how to time a 22re engine',
'how to time a chevy 350',
'how to tint windows',
'how to track a cell phone',
'how to track a cell phone for free',
'how to track a horse',
'how to track a phone number',
'how to trade options',
'how to train for a marathon',
'how to train your dragon astrid',
'how to train your dragon xbox 360',
'how to transcend',
'how to transfer contacts to note 3',
'how to transform in comic stars fighting 3 enhanced',
'how to trap a bobcat',
'how to trap a muskrat',
'how to trap a wolf',
'how to trap shoot',
'how to treat hallucinations',
'how to triangulate',
'how to triforce',
'How To Trip Plan For The FIFA World Cup',
'how to tub a car',
'how to tune a greek bouzouki',
'how to tune a weber carburetor',
'how to tune an electric guitar',
'how to tune up a stihl chainsaw',
'how to turbo',
'how to turn a crib into a toddler bed',
'how to turn fuel up on 12 valve cummins',
'how to turn off abs light',
'how to turn off airbag light',
'how to turn off daytime running lights',
'how to turn off driving mode',
'how to turn on a snowmobile',
'how to turn on assembly binding logging',
'how to turn on headlights',
'how to turn up fuel pump on 6.0 powerstroke',
'how to twerk for girls',
'how to twerk on a boy',
'how to twitch a horse',
'how to unblock tubeplus',
'how to unbrick htc one x',
'how to underseal a car',
'how to undo push fit fittings',
'how to unhook a dishwasher',
'how to uninstall windows 8',
'how to unjailbreak iphone',
'how to unjailbreak ipod touch',
'how to unlock a deadbolt without a key',
'how to unlock a kindle fire',
'how to unlock a memory card',
'how to unlock a metropcs phone',
'how to unlock a nokia 520',
'how to unlock a steering wheel',
'how to unlock coby Android tablet',
'how to unlock cursor',
'how to unlock ems sasuke',
'how to unlock galaxy s3',
'how to unlock iphone 4 verizon',
'how to unlock iphone 5 sprint',
'how to unlock keypad',
'how to unlock moto g',
'how to unlock restricted phone',
'how to unlock windows 7',
'how to unlock your computer',
'how to unroot galaxy s3',
'how to unwarp wood',
'how to update a gps',
'how to update a split level house',
'how to update fifa 13 on ps3',
'how to update rosters on nba 2k13',
'how to upgrade acer aspire one',
'how to upgrade the ice staff',
'how to upholster',
'how to upholster a car seat',
'how to upholster a chair',
'how to upholster a motorcycle seat',
'how to upholster ottoman',
'how to upload photos from Android',
'how to use a flogger',
'how to use a rawl plug',
'how to use a sextant',
'how to use a triple beam balance',
'how to use allshare',
'how to use appcake',
'how to use bootstrap',
'how to use casio',
'how to use command prompt',
'how to use corel draw',
'how to use dam',
'how to use duroil',
'how to use else if',
'how to use git',
'how to use goniometer',
'how to use google groups',
'how to use gotoassist',
'how to use herbs in resident evil 6',
'how to use htc desire c',
'how to use jmap',
'how to use k3d',
'how to use magic in god of war ascension',
'how to use medabon',
'how to use microsoft outlook',
'how to use microsoft publisher',
'how to use mixxx',
'how to use netbeans ide',
'how to use onclick',
'how to use openvas',
'how to use partograph',
'how to use pokedit',
'how to use pwdump',
'how to use quickbooks',
'how to use r',
'how to use rand',
'how to use redis',
'how to use rufus',
'how to use s beam',
'how to use seafoam',
'how to use skill points in resident evil 6',
'how to use staff of herding',
'how to use the right hand rule',
'how to use tiptronic',
'how to use tor',
'how to use twitter api',
'how to use virtualbox',
'how to use voldyne 5000',
'how to vacuum bleed power steering',
'how to value a tree',
'how to vent a dishwasher',
'how to view private instagram photos',
'how to vogue',
'how to vote no confidence',
'how to vote online',
'how to ward off evil spirits',
'how to watch football online',
'how to watch presidential debate online',
'how to watch sky tv for free',
'how to watch youtube on nokia c3',
'how to wax traps',
'how to wear a paddle holster',
'how to wear under armour',
'how to weave a sweater',
'how to weave a vest',
'how to weld a differential',
'how to weld a frame',
'how to weld sheet metal',
'how to whitewash wood',
'how to widen steelies',
'how to widen wheel arches',
'how to win on slot machines',
'how to win powerball',
'how to win the mega millions',
'how to wind coils for a generator',
'how to wire a ceiling fan',
'how to wire a house',
'how to wire a light switch',
'how to wire an outlet',
'how to wire three phase',
'how to withdraw a guilty plea',
'how to wop',
'how to work in new york',
'how to work out rate of reaction',
'how to work passbook',
'how to work with and modify the turbo hydramatic 400 transmission',
'how to worship satan',
'how to wrap a knife handle',
'how to wrap a paddle with 550 cord',
'how to wrap bruised ribs',
'how to wrap motorcycle',
'how to write a bill of exchange',
'how to write a motion',
'how to write a personal recount',
'how to write a prescription',
'how to write a rationale',
'how to write a theme essay',
'how to write numbers in standard form',
'how to xex',
'how to yf',
'how to yike',
'how to yike step by step',
'how to zydeco',
'install door closer');

global $wgLanguageCode;
$dbw = wfGetDB(DB_MASTER);

print "Step 1 of 4: Get supertitus spreadsheet data\n";
try {
	$gs = new GoogleSpreadsheet();
	$startColumn = 1;
	$endColumn = 4;
	$startRow = 2;
	$cols = $gs->getColumnData( WH_TITUS_TOP10K_GOOGLE_DOC, $startColumn, $endColumn, $startRow );
	$urlList = array();
	$pageIds = array();
	$dups = "";
	$kwl = array();
	foreach($cols as $col) {
		if(is_numeric($col[1]) && $wgLanguageCode == $col[2]) {
			$page_id = $col[1];

			//parse for comma-separated keywords on the same line
			$kws = explode(',',$col[0]);
			foreach ($kws as $keywords) {
				$kwl[$page_id] = trim($keywords);
			}
			$ids[] = $page_id;
		}
	}

	if(sizeof($kwl) < 1000 && $wgLanguageCode == "en") {
		print("ERROR: Top10k problem fetching spreadsheet. Fewer than 1000 ids found ");
		return;
	}

	if($ids) {
		if (!checkForRedirects($dbw, $ids)) return;
		//if (!checkForMissing($dbw, $ids)) return;
		checkForMissing($dbw, $ids);
	}

	$dup_kw = array();
	foreach ($kwl as $page_id => $keywords) {
		if (!$keywords) {
			print "NOKW - $page_id - $keywords\n";
			continue;
		}
		$keywords = urldecode($keywords);
		$position = $dbw->selectField('mmk.keywords', array('position'), array('title' => $keywords), __METHOD__);
		if (!$position) {
			print "NOP - $page_id - $keywords - $position\n";
			continue;
		}
		//double-check it's not already in there
		$existing_kw = $dbw->selectField('mmk.mmk_manager', array('mmk_keyword'),array('mmk_position' => $position), __METHOD__);
		if ($existing_kw) {
			print "DUP - $page_id - $existing_kw\n";
			$dup_kw[] = $existing_kw;
			continue;
		}
		$page_title = $dbw->selectField('page', array('page_title'), array('page_id' => $page_id), __METHOD__);
		if (!$page_title) {
			print "NOPT - $page_id - $keywords - $position\n";
			continue;
		}
		$cols = array(
				'mmk_position' => $position,
				'mmk_keyword' => $keywords,
				'mmk_status' => 0,
				'mmk_page_title' => $page_title,
				'mmk_page_id' => $page_id,
				'mmk_old_page_id' => 0,
				'mmk_rating' => '',
				'mmk_rating_date' => '',
				'mmk_language_code' => 'en',
				'mmk_last_updated' => 0
				);
		$dbw->insert('mmk.mmk_manager',$cols,__METHOD__);
	}

	if (count($dup_kw) > 0) {
		print "MULTIPLE PAGES IN SPREADSHEET FOR THESE KEYWORDS:\n";
		print implode("\n",$dup_kw);
	}
}
catch(Exception $e) {
	print("ERROR: Top10k problem fetching spreadsheet :" . $e->getMessage());
}

print "Step 2 of 4: Get verbatim matches\n";

//first, grab all our known keyword matches
$res = $dbw->select('mmk.mmk_manager',array('mmk_position'),'',__METHOD__);
foreach ($res as $row) {
	$pos[] = $row->mmk_position;
}
//then, grab all the verbatim matches in page (using our pre-formatted mapping tables)
$inserts = array();
$res = DatabaseHelper::batchSelect(array('mmk.tmp_pages','mmk.keywords_comp'),
			array('page_id','kc_position'),
			array('page_title = kc_keywords', " kc_position not in (".implode(',',$pos).")"),
			__METHOD__);
foreach ($res as $row) {
	//leave out the keywords & page_title and grab those on the insert
	$inserts[] = array(
				'mmk_position' => $row->kc_position,
				'mmk_status' => 0,
				'mmk_page_id' => $row->page_id,
				'mmk_old_page_id' => 0,
				'mmk_rating' => '',
				'mmk_rating_date' => '',
				'mmk_language_code' => 'en',
				'mmk_last_updated' => 0
				);
}

//finally do the inserts
foreach ($inserts as $cols) {
	if (in_array($cols['mmk_position'],$pos)) continue;
	$kw = $dbw->selectField('mmk.keywords',array('title'),array('position' => $cols['mmk_position']), __METHOD__);
	if (!$kw) continue;
	$pt = $dbw->selectField('page',array('page_title'),array('page_id' => $cols['mmk_page_id']), __METHOD__);
	if (!$pt) continue;
	$cols['mmk_keyword'] = $kw;
	$cols['mmk_page_title'] = $pt;
	$res = $dbw->insert('mmk.mmk_manager',$cols,__METHOD__);
	if ($res) $pos[] = $cols['mmk_position'];
};

print "Step 3 of 4: Set statuses to 3\n";
$dbw->update('mmk.mmk_manager', array('mmk_status' => 3), array(), __METHOD__);


print "Step 4 of 4: Set statuses to 2 from our custom array\n";
//update any already in the table
$dbw->update('mmk.mmk_manager', array('mmk_status' => 2), array('mmk_keyword in ("'.implode('","',$status2s).'")'), __METHOD__);

//import new
$res = $dbw->select('mmk.keywords', array('*'), array('title in ("'.implode('","',$status2s).'")'), __METHOD__);
foreach ($res as $row) {
	//already done?
	$count = $dbw->selectField('mmk.mmk_manager', array('count(*)'), array('mmk_keyword' => $row->title), __METHOD__);
	if ($count > 0) continue;

	//leave out the keywords & page_title and grab those on the insert
	$cols = array(
			'mmk_position' => $row->position,
			'mmk_keyword' => $row->title,
			'mmk_status' => 2,
			'mmk_page_title' => '',
			'mmk_page_id' => 0,
			'mmk_old_page_id' => 0,
			'mmk_rating' => '',
			'mmk_rating_date' => '',
			'mmk_language_code' => 'en',
			'mmk_last_updated' => 0
			);
	$dbw->insert('mmk.mmk_manager',$cols,__METHOD__);
}

print "DONE";


//copied from Titus.class.php
function checkForRedirects(&$dbr, &$ids) {
	global $wgLanguageCode;

	$query = "select page_id,page_title  from " . Misc::getLangDB($wgLanguageCode) . ".page where page_is_redirect=1 AND page_id in (" . implode($ids,",") . ")";
	$res = $dbr->query($query,__METHOD__);
	$redirects = "";
	foreach($res as $row) {
		if($redirects == "") {
			$redirects = "The following pages are redirects:\n";
		}
		else {
			$redirects .= "\n";
		}
		$redirects .= getBaseUrl() . '/' . $row->page_title . " (" . $row->page_id . ")";

	}
	if($redirects != "") {
		print "\n\nREDIRECTS:\n".$redirects."\n\n";
		return false;
	}
	return true;
}
function checkForMissing(&$dbr, &$ids) {
	global $wgLanguageCode;
	$query = "select page_id  from " . Misc::getLangDB($wgLanguageCode) . ".page where page_id in (" . implode($ids,",") . ")";
	$res = $dbr->query($query,__METHOD__);
	$foundIds = array();
	foreach($res as $row) {
		$foundIds[] = $row->page_id;
	}
	$missing = array_diff($ids, $foundIds);
	if(sizeof($missing) > 0) {
		print "The following articles were not found and may have been deleted (" . implode($missing,',') . ")\n";
		return false;
	}
	return true;
}

function getBaseUrl() {
	global $wgLanguageCode;
	if($wgLanguageCode == "en") {
		return("http://www.wikihow.com");
	}
  else {
		return("http://" . $wgLanguageCode . ".wikihow.com");
  }
}
